import { Saga, Season, Timeline, TimelineData, Volume } from '.';
import {
    getArcWidth,
    getChapterWidth,
    getEpisodeWidth,
    getSagaWidth,
    getSeasonWidth,
    getVolumeWidth,
} from '../shared/lib/helpers';
import { pad, Tuple } from '../shared/lib/util';

const SEASON_HEIGHT = 742;
const EPISODE_HEIGHT = SEASON_HEIGHT * 0.33;
const VOLUME_HEIGHT = 1579;
const CHAPTER_HEIGHT = 100;
const ARC_HEIGHT = VOLUME_HEIGHT * 0.8;
const SAGA_HEIGHT = 150 + ARC_HEIGHT;

const VOLUMES_TOTAL = 24;
const SAGAS_TOTAL = 2;
const SEASONS_TOTAL = 4;

const volumeTitle = (timeline: TimelineData, idx: number) =>
    timeline.volumes[idx]!.chapters[0]!.title(timeline, idx);
const volumeCover = (_: TimelineData, idx: number) => `Volume_${pad(idx + 1)}`;
const episodeTitle = (idx: number) => (timeline: TimelineData) =>
    timeline.volumes.flatMap(v => v.chapters)[idx]!.title(timeline, idx);
const episodeCover = (_: TimelineData, idx: number) => (idx + 1).toString();

export const CSM_TIMELINE: Timeline = {
    layout: {
        season: {
            type: 'season',
            height: SEASON_HEIGHT,
            width: getSeasonWidth,
            blankfontSize: 250,
            titleFontSize: 100,
            numberProcessor: n => (n - 1).toString(),
            sectionLink: 'Chainsaw Man (Anime)',
            wikiLink: title => title,
            subTimeline: {
                type: 'episode',
                height: EPISODE_HEIGHT,
                width: getEpisodeWidth,
                scale: 1.2,
                titleProcessor: (title, n) => `${title}\n(Episode ${n})`,
                blankfontSize: 42,
                titleFontSize: 42,
                sectionLink: 'Chainsaw_Man_(Anime)#Episodes',
                wikiLink: (_, n) => `Episode_${n}`,
            },
        },
        saga: {
            type: 'saga',
            height: SAGA_HEIGHT,
            width: getSagaWidth,
            titleProcessor: title => `${title} saga`,
            blankfontSize: 100,
            titleFontSize: 100,
            sectionLink: 'Story Arcs',
            wikiLink: title => `${title} Saga`,
            subTimeline: {
                type: 'arc',
                height: ARC_HEIGHT,
                width: getArcWidth,
                titleProcessor: title => `${title} arc`,
                blankfontSize: 100,
                titleFontSize: 100,
                sectionLink: 'Story Arcs',
                wikiLink: title => `${title} arc`,
            },
        },
        timeline: {
            type: 'timeline',
        },
        chapter: {
            type: 'chapter',
            height: CHAPTER_HEIGHT,
            width: getChapterWidth,
            fit: 'contain',
            backgroundColor: 'white',
            blankfontSize: 45,
            titleFontSize: 45,
            sectionLink: 'Chainsaw_Man_(Manga)#Chapters',
            wikiLink: (_, n) => `Chapter_${n}`,
            focusable: true,
        },
        volume: {
            type: 'volume',
            height: VOLUME_HEIGHT,
            width: getVolumeWidth,
            defaultCoverPosition: 'top',
            titleProcessor: (title, n) => `${title}\n(Volume ${n})`,
            blankfontSize: 500,
            titleFontSize: 100,
            sectionLink: 'Chainsaw_Man_(Manga)#Chapters',
            wikiLink: (_, n) => `Volume_${n}`,
        },
    },
    data: {
        title: 'Chainsaw Man',
        volumes: [
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Dog & Chainsaw',
                        date: 'December 3, 2018',
                        pages: 54,
                        cover: 'Volume_01_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'The Place Where Pochita Is',
                        date: 'December 10, 2018',
                        pages: 25,
                        cover: 'Volume_01_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Arrival in Tokyo',
                        date: 'December 17, 2018',
                        pages: 23,
                        cover: 'Volume_01_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Power',
                        date: 'December 22, 2018',
                        pages: 19,
                        cover: 'Volume_01_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'A Way to Touch Some Boobs',
                        date: 'January 7, 2019',
                        pages: 19,
                        cover: 'Volume_01_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Service',
                        date: 'January 21, 2019',
                        pages: 19,
                        cover: 'Volume_01_Pochita_Sketch_7',
                    },
                    {
                        title: () => "Meowy's Whereabouts",
                        date: 'January 28, 2019',
                        pages: 19,
                        cover: 'Volume_01_Pochita_Sketch_8',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Chainsaw vs. Bat',
                        date: 'February 4, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Rescue',
                        date: 'February 11, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Kon',
                        date: 'February 18, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Compromise',
                        date: 'February 25, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Squeeze',
                        date: 'March 4, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Gun Devil',
                        date: 'March 11, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'French Kiss',
                        date: 'March 18, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Endless 8th Floor',
                        date: 'March 25, 2019',
                        pages: 21,
                        cover: 'Volume_02_Pochita_Sketch_8',
                    },
                    {
                        title: () => 'The First Taste',
                        date: 'April 1, 2019',
                        pages: 19,
                        cover: 'Volume_02_Pochita_Sketch_9',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Kill Denji',
                        date: 'April 8, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Chainsaw vs Eternity',
                        date: 'April 15, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Nobel Prize',
                        date: 'April 22, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Drinking',
                        date: 'April 27, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Taste of a Kiss',
                        date: 'May 13, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Cola-Flavor Chupa Chups',
                        date: 'May 20, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Gunfire',
                        date: 'May 27, 2019',
                        pages: 21,
                        cover: 'Volume_03_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Curse',
                        date: 'June 3, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_8',
                    },
                    {
                        title: () => 'Ghost, Snake, Chainsaw',
                        date: 'June 10, 2019',
                        pages: 19,
                        cover: 'Volume_03_Pochita_Sketch_9',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Gun is Mightier',
                        date: 'June 17, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'From Kyoto',
                        date: 'June 24, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Secrets & Lies',
                        date: 'July 1, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Perfect Score',
                        date: 'July 8, 2019',
                        pages: 21,
                        cover: 'Volume_04_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Bruised & Battered',
                        date: 'July 13, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'The Future Rules',
                        date: 'July 22, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Over and Over Again',
                        date: 'July 29, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Mission Start',
                        date: 'August 5, 2019',
                        pages: 20,
                        cover: 'Volume_04_Pochita_Sketch_9',
                    },
                    {
                        title: () => 'Full Team',
                        date: 'August 18, 2019',
                        pages: 19,
                        cover: 'Volume_04_Pochita_Sketch_10',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Minor',
                        date: 'August 26, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Katana vs. Chainsaw',
                        date: 'September 2, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Train, Head, Chainsaw',
                        date: 'September 9, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Easy Revenge!',
                        date: 'September 14, 2019',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: () => 'Tearjerker',
                        date: 'September 21, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Love, Flower, Chainsaw',
                        date: 'September 30, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Before the Storm',
                        date: 'October 7, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Teach Me How To Swim',
                        date: 'October 12, 2019',
                        pages: 19,
                        cover: 'Volume_05_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Jane Fell Asleep in the Church',
                        date: 'October 21, 2019',
                        pages: 22,
                        cover: 'Volume_05_Pochita_Sketch_8',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Boom Boom Boom',
                        date: 'October 28, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'A Fine Day for Explosions',
                        date: 'November 2, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Massacre Melody',
                        date: 'November 11, 2019',
                        pages: 21,
                        cover: 'Volume_06_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Luck with Women',
                        date: 'November 18, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Kaboom Kaboom Kaboom',
                        date: 'November 25, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Shark Hurricane',
                        date: 'December 2, 2019',
                        pages: 21,
                        cover: 'Volume_06_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Sharknado',
                        date: 'December 9, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Dark Diving',
                        date: 'December 15, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_8',
                    },
                    {
                        title: () => 'Lost Love, Flower, Chainsaw',
                        date: 'December 23, 2019',
                        pages: 19,
                        cover: 'Volume_06_Pochita_Sketch_9',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'In a Dream',
                        date: 'January 3, 2020',
                        pages: 21,
                        cover: 'Volume_07_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'To Go to Enoshima',
                        date: 'January 20, 2020',
                        pages: 19,
                        cover: 'Volume_07_Pochita_Sketch_2',
                    },
                    {
                        title: () => "Let's Go",
                        date: 'January 27, 2020',
                        pages: 19,
                        cover: 'Volume_07_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'A Curse and A First',
                        date: 'February 3, 2020',
                        pages: 19,
                        cover: 'Volume_07_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Suddenly',
                        date: 'February 10, 2020',
                        pages: 19,
                        cover: 'Volume_07_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Yutaro Kurose',
                        date: 'February 17, 2020',
                        pages: 19,
                        cover: 'Volume_07_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Mess',
                        date: 'February 22, 2020',
                        pages: 22,
                        cover: 'Volume_07_Pochita_Sketch_7',
                    },
                    {
                        title: () => "Quanxi and Fiends' 49-Person Massacre",
                        date: 'March 2, 2020',
                        pages: 21,
                        cover: 'Volume_07_Pochita_Sketch_8',
                    },
                    {
                        title: () => 'News Reporter',
                        date: 'March 9, 2020',
                        pages: 21,
                        cover: 'Volume_07_Pochita_Sketch_9',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Super Mess',
                        date: 'March 16, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Trip to Hell',
                        date: 'March 23, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Welcome to Hell',
                        date: 'March 30, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'The Darkness Devil',
                        date: 'April 6, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Woof!',
                        date: 'April 13, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'The First Devil Hunter',
                        date: 'April 27, 2020',
                        pages: 21,
                        cover: 'Volume_08_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Dark Power',
                        date: 'May 11, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Shining Power',
                        date: 'May 18, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_8',
                    },
                    {
                        title: () => 'Pinch',
                        date: 'May 25, 2020',
                        pages: 19,
                        cover: 'Volume_08_Pochita_Sketch_9',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Bath',
                        date: 'June 1, 2020',
                        pages: 22,
                        cover: 'Volume_09_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'All Together',
                        date: 'June 7, 2020',
                        pages: 19,
                        cover: 'Volume_09_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Everyday Life No More',
                        date: 'June 15, 2020',
                        pages: 21,
                        cover: 'Volume_09_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'What the Waves Say',
                        date: 'June 22, 2020',
                        pages: 19,
                        cover: 'Volume_09_Pochita_Sketch_4',
                    },
                    {
                        title: () => '9, 12',
                        date: 'June 26, 2020',
                        pages: 19,
                        cover: 'Volume_09_Pochita_Sketch_5',
                    },
                    {
                        title: () => "Don't Open It",
                        date: 'July 5, 2020',
                        pages: 19,
                        cover: 'Volume_09_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'Ring Ring Ring',
                        date: 'July 12, 2020',
                        pages: 19,
                        cover: 'Volume_09_Pochita_Sketch_7',
                    },
                    {
                        title: () => 'Snowball Fight',
                        date: 'July 19, 2020',
                        pages: 19,
                        cover: 'Volume_09_Pochita_Sketch_8',
                    },
                    {
                        title: () => 'Play Catch',
                        date: 'August 2, 2020',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "A Dog's Feeling",
                        date: 'August 10, 2020',
                        pages: 19,
                        cover: 'Volume_10_Pochita_Sketch',
                    },
                    {
                        title: () => 'Paw',
                        date: 'August 23, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Always Eat a Hearty Breakfast',
                        date: 'August 30, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Death, Resurrection, Chainsaw',
                        date: 'September 6, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hero of Hell',
                        date: 'September 13, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Bloody Good Gut Feeling',
                        date: 'September 20, 2020',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Date Chainsaw',
                        date: 'September 27, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Chainsaw Man Vs. the Horrifying Weapon Humans',
                        date: 'October 4, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Star Chainsaw',
                        date: 'October 11, 2020',
                        pages: 19,
                        cover: 'Volume_10_Denji_Sketch',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "Go Get 'Em, Chainsaw Man",
                        date: 'October 16, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Super Power',
                        date: 'October 26, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Power, Power, Power',
                        date: 'November 2, 2020',
                        pages: 19,
                        cover: 'Volume_11_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Vanilla Sky',
                        date: 'November 9, 2020',
                        pages: 21,
                        cover: 'Volume_11_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'You & Crappy Movies',
                        date: 'November 16, 2020',
                        pages: 19,
                        cover: 'Volume_11_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Chainsaw Man vs. the Weapon Humans',
                        date: 'November 21, 2020',
                        pages: 19,
                        cover: 'Volume_11_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Chainsaw Man vs. Control Devil',
                        date: 'November 30, 2020',
                        pages: 19,
                        cover: 'Volume_11_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'This Kind of Taste',
                        date: 'December 7, 2020',
                        pages: 19,
                        cover: 'Volume_11_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'I, Love, Chainsaw',
                        date: 'December 14, 2020',
                        pages: 23,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Bird and War',
                        date: 'July 13, 2022',
                        pages: 54,
                        cover: 'Volume_12_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Two Birds',
                        date: 'July 20, 2022',
                        pages: 24,
                        cover: 'Volume_12_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'How to Walk Shoeless',
                        date: 'July 27, 2022',
                        pages: 19,
                        cover: 'Volume_12_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'After School Devil Hunters',
                        date: 'August 3, 2022',
                        pages: 19,
                        cover: 'Volume_12_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Save the Cat',
                        date: 'August 17, 2022',
                        pages: 48,
                        cover: null,
                    },
                    {
                        title: () => 'Denji Dream',
                        date: 'August 31, 2022',
                        pages: 21,
                        cover: 'Volume_12_Pochita_Sketch_5',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Spoiler',
                        date: 'September 14, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Red Hot',
                        date: 'September 28, 2022',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Bonfire',
                        date: 'October 12, 2022',
                        pages: 17,
                        cover: 'Volume_13_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'School Attacker',
                        date: 'October 19, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Something Important to Asa',
                        date: 'October 26, 2022',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'The Easy Way to Stop Bullying',
                        date: 'November 2, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Ring in the Night',
                        date: 'November 9, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Aha Ha Ha Ha',
                        date: 'November 16, 2022',
                        pages: 17,
                        cover: 'Volume_13_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Between Cat and Criminal',
                        date: 'November 23, 2022',
                        pages: 27,
                        cover: 'Volume_13_Pochita_Sketch_3',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'I Wanna See Penguins!',
                        date: 'December 7, 2022',
                        pages: 19,
                        cover: 'Volume_14_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Endless Aquarium',
                        date: 'December 21, 2022',
                        pages: 24,
                        cover: 'Volume_14_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'High Schoolers These Days',
                        date: 'December 28, 2022',
                        pages: 11,
                        cover: 'Volume_14_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Taste of Starfish',
                        date: 'January 4, 2023',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Penguin and Weapon',
                        date: 'January 11, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Saying Goodbye',
                        date: 'January 18, 2023',
                        pages: 19,
                        cover: 'Volume_14_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Thief',
                        date: 'February 1, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Triangle',
                        date: 'February 15, 2023',
                        pages: 16,
                        cover: 'Volume_14_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Theory of Happiness',
                        date: 'February 22, 2023',
                        pages: 16,
                        cover: 'Volume_14_Pochita_Sketch_6',
                    },
                    {
                        title: () => 'The Prophecies',
                        date: 'March 8, 2023',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "Hors D'oeuvre",
                        date: 'March 15, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Soup',
                        date: 'March 29, 2023',
                        pages: 17,
                        cover: 'Volume_15_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Apple Thief',
                        date: 'April 5, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Food Fight',
                        date: 'April 12, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Save the Asa',
                        date: 'April 19, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Main Dish',
                        date: 'April 26, 2023',
                        pages: 15,
                        cover: 'Volume_15_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Save Me, Chainsaw Man',
                        date: 'May 10, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Kill Building',
                        date: 'May 24, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Taste of Crap',
                        date: 'May 31, 2023',
                        pages: 19,
                        cover: 'Volume_15_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Protection',
                        date: 'June 14, 2023',
                        pages: 15,
                        cover: 'Volume_15_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Chainsaw Man Protest',
                        date: 'June 21, 2023',
                        pages: 16,
                        cover: 'Volume_15_Pochita_Sketch_5',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Ordinary Happiness',
                        date: 'June 28, 2023',
                        pages: 18,
                        cover: 'Volume_16_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Sentimental Drive',
                        date: 'July 12, 2023',
                        pages: 22,
                        cover: 'Volume_16_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Normal Life',
                        date: 'July 19, 2023',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Chu Chu Lovely Muni Muni Mura Mura',
                        date: 'July 26, 2023',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'Sword Man',
                        date: 'August 9, 2023',
                        pages: 19,
                        cover: 'Volume_16_Pochita_Sketch_3',
                    },
                    {
                        title: () => "A Chair's Feelings",
                        date: 'August 16, 2023',
                        pages: 17,
                        cover: 'Volume_16_Pochita_Sketch_4',
                    },
                    {
                        title: () => 'Scales',
                        date: 'August 23, 2023',
                        pages: 19,
                        cover: 'Volume_16_Pochita_Sketch_5',
                    },
                    {
                        title: () => 'Normal Life Plus',
                        date: 'August 30, 2023',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Denji Fan Club',
                        date: 'September 13, 2023',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Rawr',
                        date: 'September 20, 2023',
                        pages: 15,
                        cover: 'Volume_16_Pochita_Sketch_6',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Guns, Nails, Katana',
                        date: 'September 27, 2023',
                        pages: 15,
                        cover: 'Volume_17_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Kumbaya',
                        date: 'October 11, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Chainsaw Man War',
                        date: 'October 18, 2023',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'Cremation',
                        date: 'November 1, 2023',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Room 606 Sword',
                        date: 'November 15, 2023',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => "Devil's Choice",
                        date: 'November 22, 2023',
                        pages: 20,
                        cover: 'Volume_17_Pochita_Sketch_2',
                    },
                    {
                        title: () => "Dream's Next Stage",
                        date: 'December 6, 2023',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'The Return of Chainsaw Man',
                        date: 'December 20, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Massage',
                        date: 'January 10, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chainsaw Man Hunters',
                        date: 'January 24, 2024',
                        pages: 19,
                        cover: 'Volume_17_Pochita_Sketch_3',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'All Pets',
                        date: 'January 31, 2024',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'The Old Me',
                        date: 'February 14, 2024',
                        pages: 16,
                        cover: 'Volume_18_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Whup Whup Whup Whup Bzzz Split Split',
                        date: 'February 28, 2024',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'College Fund',
                        date: 'March 6, 2024',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Gyohnee Guillotine',
                        date: 'March 13, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Attack on Samurai',
                        date: 'March 20, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'That For Which The Heart Beats',
                        date: 'March 27, 2024',
                        pages: 16,
                        cover: 'Volume_18_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Chainsaw Man Puzzle',
                        date: 'April 3, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome',
                        date: 'April 10, 2024',
                        pages: 17,
                        cover: 'Volume_18_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Dream Balls',
                        date: 'April 24, 2024',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'Charred Remains',
                        date: 'May 1, 2024',
                        pages: 16,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Everyday Scenery',
                        date: 'May 15, 2024',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Rain, Brothel, Removal',
                        date: 'May 22, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Super Smooch',
                        date: 'June 5, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Kiss, Love, Sperm',
                        date: 'June 12, 2024',
                        pages: 15,
                        cover: 'Volume_19_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Hands and Adaptation',
                        date: 'June 26, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'How to Eat Sushi',
                        date: 'July 3, 2024',
                        pages: 15,
                        cover: 'Volume_19_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Special Division 5',
                        date: 'July 17, 2024',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Bzzz! Boom! Chomp!',
                        date: 'July 24, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Hard of Hearing',
                        date: 'August 7, 2024',
                        pages: 15,
                        cover: 'Volume_19_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Ayyy, Aging',
                        date: 'August 14, 2024',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'Both Hands',
                        date: 'August 21, 2024',
                        pages: 16,
                        cover: 'Volume_19_Pochita_Sketch_4',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Two Children',
                        date: 'September 4, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Trigger Finger',
                        date: 'September 18, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Gun Goddess',
                        date: 'September 25, 2024',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'Vamvagah',
                        date: 'October 2, 2024',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => "Aging's World",
                        date: 'October 16, 2024',
                        pages: 18,
                        cover: 'Volume_20_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Trees on the Mind',
                        date: 'October 23, 2024',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'Cute',
                        date: 'November 6, 2024',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Barf, Head, Perv',
                        date: 'November 13, 2024',
                        pages: 15,
                        cover: 'Volume_20_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Run, Denji!',
                        date: 'November 20, 2024',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Stomach in Another World',
                        date: 'November 27, 2024',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Yank, Blorsh, Bdroom',
                        date: 'December 11, 2024',
                        pages: 17,
                        cover: 'Volume_20_Pochita_Sketch_3',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Barf!',
                        date: 'December 18, 2024',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Octopus, War, Chainsaw',
                        date: 'January 1, 2025',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Heart Pass, Octopus',
                        date: 'January 8, 2025',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'To Their Respective Worlds',
                        date: 'January 15, 2025',
                        pages: 15,
                        cover: 'Volume_21_Pochita_Sketch_1',
                    },
                    {
                        title: () => "Cuz I'm a Devil",
                        date: 'January 29, 2025',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'How Devils Play',
                        date: 'February 5, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Burning Kiss',
                        date: 'February 12, 2025',
                        pages: 13,
                        cover: 'Volume_21_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Fun School Festival',
                        date: 'February 26, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Kill Me Tears',
                        date: 'March 5, 2025',
                        pages: 15,
                        cover: 'Volume_21_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Chainsaw Man to the Rescue!',
                        date: 'March 12, 2025',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => '3 Seconds',
                        date: 'March 26, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => "It's Fami!",
                        date: 'April 2, 2025',
                        pages: 15,
                        cover: 'Volume_21_Pochita_Sketch_4',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Enjoy Your Food',
                        date: 'April 9, 2025',
                        pages: 15,
                        cover: 'Volume_22_Pochita_Sketch_1',
                    },
                    {
                        title: () => 'Toxic Couple',
                        date: 'April 16, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Terror Looks Like This!',
                        date: 'April 30, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Devil Combination',
                        date: 'May 7, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Human Shield',
                        date: 'May 21, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'With One Life',
                        date: 'May 28, 2025',
                        pages: 15,
                        cover: 'Volume_22_Pochita_Sketch_2',
                    },
                    {
                        title: () => 'Who?',
                        date: 'June 11, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Chest, Woman, Apology',
                        date: 'June 18, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Budda Budda Budda Budda!',
                        date: 'July 2, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Changed My Mind',
                        date: 'July 9, 2025',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Terrifying Weapon',
                        date: 'July 23, 2025',
                        pages: 15,
                        cover: 'Volume_22_Pochita_Sketch_3',
                    },
                    {
                        title: () => 'Peace',
                        date: 'July 30, 2025',
                        pages: 15,
                        cover: 'Volume_22_Pochita_Sketch_4',
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'War, Panties, Chainsaw',
                        date: 'August 13, 2025',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Really Good Girl',
                        date: 'August 20, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Role',
                        date: 'September 3, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Bff, Creak, Door',
                        date: 'September 17, 2025',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Declaration of War',
                        date: 'September 24, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Yearning',
                        date: 'October 1, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Two Good People',
                        date: 'October 15, 2025',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Eat Me',
                        date: 'October 29, 2025',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'The Bereft',
                        date: 'November 5, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Bonds and Michigan',
                        date: 'November 12, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Safe Battle',
                        date: 'November 26, 2025',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'Denji Man',
                        date: 'December 3, 2025',
                        pages: 15,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: null,
                chapters: [
                    {
                        title: () => 'Ultimate Armor',
                        date: 'December 17, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Moon, Spear, Spear',
                        date: 'December 24, 2025',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Barf, Motorcycle, Hell',
                        date: 'January 7, 2026',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => "Locust's Home",
                        date: 'January 14, 2026',
                        pages: 14,
                        cover: null,
                    },
                    {
                        title: () => 'The Taste of Shrimp and Blood',
                        date: 'January 21, 2026',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: () => 'Dove',
                        date: 'February 4, 2026',
                        pages: 15,
                        cover: null,
                    },
                ],
            },
        ] as const satisfies Tuple<Volume, typeof VOLUMES_TOTAL>,
        sagas: [
            {
                title: 'Public Safety',
                cover: null,
                chapters: { from: 1, to: 97 },
                arcs: [
                    {
                        title: 'Introduction',
                        cover: 'Denji_fighting_zombies',
                        offset: { x: 130, y: 0 },
                        chapters: { from: 1, to: 4 },
                    },
                    {
                        title: 'Bat Devil',
                        cover: 'Denji_attacking_the_Bat_Devil',
                        offset: { x: 220, y: 0 },
                        chapters: { from: 5, to: 13 },
                    },
                    {
                        title: 'Eternity Devil',
                        cover: 'Denji_fighting_the_Eternity_Devil',
                        offset: { x: 0, y: 0 },
                        chapters: { from: 14, to: 22 },
                    },
                    {
                        title: 'Katana Man',
                        cover: 'Denji_engaging_the_Katana_Man',
                        offset: { x: 0, y: 150 },
                        chapters: { from: 23, to: 38 },
                    },
                    {
                        title: 'Bomb Girl',
                        cover: 'Denji_engaging_Reze',
                        offset: { x: 0, y: 90 },
                        chapters: { from: 39, to: 52 },
                    },
                    {
                        title: 'International Assassins',
                        cover: 'Denji_engaging_Santa_Claus',
                        offset: { x: 0, y: 750 },
                        chapters: { from: 53, to: 70 },
                    },
                    {
                        title: 'Gun Devil',
                        cover: 'Chainsaw_vs_Gun_Fiend',
                        offset: { x: 0, y: 250 },
                        chapters: { from: 71, to: 79 },
                    },
                    {
                        title: 'Control Devil',
                        cover: 'Hybrids_attacking_Chainsaw',
                        offset: { x: 0, y: 120 },
                        chapters: { from: 80, to: 97 },
                    },
                ],
            },
            {
                title: 'Academy',
                cover: null,
                chapters: { from: 98 },
                arcs: [
                    {
                        title: 'Justice Devil',
                        cover: 'Asa_vs_Yuko_as_Justice_Devil',
                        offset: { x: 0, y: 1 },
                        chapters: { from: 98, to: 111 },
                    },
                    {
                        title: 'Dating Denji',
                        cover: 'Dating_Denji_arc_infobox_picture',
                        offset: { x: 150, y: 0 },
                        chapters: { from: 112, to: 120 },
                    },
                    {
                        title: 'Falling Devil',
                        cover: 'Denji_tears_through_the_Falling_Devil',
                        offset: { x: 0, y: 0 },
                        chapters: { from: 121, to: 131 },
                    },
                    {
                        title: 'Chainsaw Man Church',
                        cover: 'Denji_and_Miri_impale_each_other',
                        offset: { x: 0, y: 430 },
                        chapters: { from: 132, to: 155 },
                    },
                    {
                        title: 'Aging Devil',
                        cover: 'Chainsaw_vs_Aging',
                        offset: { x: 0, y: 250 },
                        chapters: { from: 156, to: 190 },
                    },
                    {
                        title: 'Current',
                        cover: "Pochita_surrounded_by_Yoru's_Devil_Army",
                        offset: { x: 0, y: 0 },
                        chapters: { from: 191 },
                    },
                ],
            },
        ] as const satisfies Tuple<Saga, typeof SAGAS_TOTAL>,
        seasons: [
            {
                title: 'Chainsaw Man (Anime)',
                cover: () => 'Chainsaw_Man_Anime_Key_Visual_1',
                offset: { x: 0, y: 1900 },
                chapters: { from: 1, to: 38 },
                episodes: [
                    {
                        title: episodeTitle(0),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 1, to: 1 },
                    },
                    {
                        title: episodeTitle(2),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 2, to: 5 },
                    },
                    {
                        title: episodeTitle(6),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 5, to: 8 },
                    },
                    {
                        title: episodeTitle(8),
                        cover: episodeCover,
                        offset: { x: 20, y: 0 },
                        chapters: { from: 9, to: 12 },
                    },
                    {
                        title: episodeTitle(12),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 12, to: 15 },
                    },
                    {
                        title: episodeTitle(16),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 15, to: 18 },
                    },
                    {
                        title: episodeTitle(20),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 18, to: 21 },
                    },
                    {
                        title: episodeTitle(22),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 22, to: 25 },
                    },
                    {
                        title: episodeTitle(26),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 25, to: 28 },
                    },
                    {
                        title: episodeTitle(29),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 29, to: 31 },
                    },
                    {
                        title: episodeTitle(32),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 31, to: 35 },
                    },
                    {
                        title: episodeTitle(35),
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        chapters: { from: 35, to: 38 },
                    },
                ],
            },
            {
                title: 'Chainsaw Man – The Movie: Reze Arc',
                cover: () => 'Chainsaw_Man_Movie_-_Reze_Arc_Key_Visual_1',
                offset: { x: 0, y: 800 },
                chapters: { from: 38, to: 52 },
                episodes: [],
            },
            {
                title: 'Chainsaw Man: Assassins Arc',
                cover: () => 'Chainsaw_Man_TV_Anime_Key_Visual_2',
                offset: { x: 0, y: 5100 },
                chapters: { from: 53, to: 97 },
                episodes: [],
            },
            {
                chapters: { from: 98 },
            },
        ] as const satisfies Tuple<Season, typeof SEASONS_TOTAL>,
        splitChapters: {
            5: 10,
            12: 1,
            15: 10,
            18: 12,
            25: 14,
            31: 18,
            35: 6,
            38: 22,
        },
        wikiBase: 'https://chainsaw-man.fandom.com/wiki/',
        smallImages: {
            'scroller-or-favicon': 'pochita',
            'read-info': 'pochita2',
            'toggle-unbounded-chapter-width': 'pochita3',
            'toggle-cross-lines': 'pochita6',
            'open-chapter-calendar': 'pochita4',
            'toggle-always-show-titles': 'pochita5',
            'capture-timeline': 'pochita7',
        },
        socialLinks: [
            {
                name: 'Manga Plus',
                url: 'https://mangaplus.shueisha.co.jp/titles/100037',
            },
            {
                name: 'VIZ Media',
                url: 'https://www.viz.com/shonenjump/chapters/chainsaw-man',
            },
            {
                name: "Author's Twitter",
                url: 'https://x.com/nagayama_koharu',
            },
            {
                name: 'Official Site',
                url: 'https://www.shonenjump.com/j/rensai/chainsaw.html',
            },
            {
                name: 'Anime Website',
                url: 'https://chainsawman.dog/',
            },
        ],
    },
};
