/* eslint-disable max-lines */ // a lot of data for a title
import { Tuple } from '@shared/lib/util';
import {
    ArrowRangeIcon,
    ListIcon,
    InfoIcon,
    ExpandIcon,
    FitIcon,
    CalendarIcon,
    TitleIcon,
    CameraIcon,
} from '@shared/ui/icons';
import { Season, Timeline, Volume } from '@timelines/types';

const SEASON_HEIGHT = 2000;
const EPISODE_HEIGHT = SEASON_HEIGHT * 0.2;
const VOLUME_HEIGHT = 1425;
const CHAPTER_HEIGHT = 100;

type VolumesTotal = 23;
type SeasonsTotal = 4;

const volumeTitle = (n: number) => `Volume ${n}`;
const volumeCover = (n: number) => `Volume_${n}`;
const seasonCover = (n: number) => `Season_${n}`;
const episodeCover = (n: number) => `Episode_${n}`;

export const DHD_TIMELINE: Timeline = {
    layout: {
        season: {
            type: 'season',
            height: SEASON_HEIGHT,
            blankfontSize: 250,
            titleFontSize: 100,
            sectionLink: 'Dorohedoro (anime)',
            wikiLink: () => 'Dorohedoro (anime)',
            subTimeline: {
                type: 'episode',
                height: EPISODE_HEIGHT,
                scale: 1.2,
                titleProcessor: (title, n) => `${title}\n(Episode ${n})`,
                blankfontSize: 42,
                titleFontSize: 42,
                sectionLink: 'Dorohedoro_(Anime)#Episodes',
                wikiLink: (_, n) => `Episode ${n}`,
                focusable: true,
            },
        },
        timeline: {
            type: 'timeline',
        },
        chapter: {
            type: 'chapter',
            height: CHAPTER_HEIGHT,
            fit: 'contain',
            backgroundColor: 'white',
            blankfontSize: 45,
            titleFontSize: 45,
            sectionLink: 'Volumes and Chapters',
            wikiLink: (_, n) => `Chapter ${n}`,
            focusable: true,
        },
        volume: {
            type: 'volume',
            height: VOLUME_HEIGHT,
            defaultCoverPosition: 'top',
            blankfontSize: 500,
            titleFontSize: 100,
            sectionLink: 'Volumes and Chapters',
            wikiLink: (_, n) => `Volume ${n}`,
        },
    },
    data: {
        title: 'Dorohedoro',
        volumes: [
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Kaiman',
                        date: 'December 30, 2000',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Hungry Bug',
                        date: 'February 28, 2001',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'The Guy from the Nightmare',
                        date: 'April 30, 2001',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'In The Bag',
                        date: 'June 30, 2001',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Silence At The Table',
                        date: 'August 31, 2001',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Magic User From The Next Town',
                        date: 'November 1, 2001',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Night of The Living Dead',
                        date: 'July 1, 2002',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'Bloody Fight',
                        date: 'August 1, 2002',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Lizards Can Dance Too',
                        date: 'September 1, 2002',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Roast Duck With Magic User Sauce',
                        date: 'October 1, 2002',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Competition of the So-Called Underworld',
                        date: 'November 1, 2002',
                        pages: 28,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Formal Attire Requested',
                        date: 'December 1, 2002',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Another Year in the Hole',
                        date: 'January 1, 2003',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Kaiman in Wonderland',
                        date: 'April 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Secret story of the fire toilet',
                        date: 'May 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Girl Who Sells Smoke',
                        date: 'June 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Ripe Mushrooms En Masse',
                        date: 'July 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The First Smoke',
                        date: 'August 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Sewer Elegy',
                        date: 'September 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The All-Star - Dream Game',
                        date: 'October 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The All-Star - Dream Game Heats Up!!',
                        date: 'November 1, 2003',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: () => 'Reptiles Spawn',
                        date: 'December 1, 2003',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'A Good Day To Leave',
                        date: 'January 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Lalala Monsterman',
                        date: 'February 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Splendid & Exuberant',
                        date: 'March 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Blue Night Land',
                        date: 'April 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Ah, Flower Smoke',
                        date: 'May 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Awesome Meatpie',
                        date: 'June 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'A Macabre Mushroom Appears!',
                        date: 'July 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Welcome Mushroom-chan!',
                        date: 'August 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Lonely Kaiman',
                        date: 'September 1, 2004',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: () => 'Odd Person In The Night',
                        date: 'October 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Before Nightmare',
                        date: 'November 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Manju Terror',
                        date: 'December 1, 2004',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Yakimo Rendezvous',
                        date: 'January 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Boss',
                        date: 'February 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "Let's Meet At The Snack Bar",
                        date: 'April 1, 2005',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: () => 'Meat Bags Free For All',
                        date: 'May 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Battle - Boy Meets Girl',
                        date: 'June 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Recycling',
                        date: 'July 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'A Dinner In Good Company',
                        date: 'August 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Smoky Drive!',
                        date: 'September 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Terror At The Gory House- Mass Slaughter',
                        date: 'October 1, 2005',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Meoto Zenzai',
                        date: 'November 1, 2005',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'Crosseye Doll',
                        date: 'December 1, 2005',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Mastema Sub Promenade',
                        date: 'February 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Cross-Eye Tragedy',
                        date: 'March 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Sweet Home',
                        date: 'April 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Sparkling ★ Youth',
                        date: 'May 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () =>
                            'Going Round And Round! Memories return...',
                        date: 'July 1, 2006',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Comeback Hole',
                        date: 'August 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Golden Beetles are Rich',
                        date: 'September 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Cute Butchery',
                        date: 'October 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Door To The Past',
                        date: 'November 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Final Night - Two People',
                        date: 'December 1, 2006',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Chance Encounter - Rain',
                        date: 'January 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Good Company is the Best Shortcut',
                        date: 'March 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Small Change Love',
                        date: 'April 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Mushroom Revival',
                        date: 'May 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Farewell, Kaiman',
                        date: 'June 1, 2007',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Magic and Carpets',
                        date: 'July 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Hearts Ablaze',
                        date: 'September 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Memory Bubbles',
                        date: 'October 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Many Feelings - One True Motive',
                        date: 'November 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Cross-Dude-Expedition',
                        date: 'December 1, 2007',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Reunion of the Freaks',
                        date: 'January 1, 2008',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'Juncture Skills',
                        date: 'February 1, 2008',
                        pages: 32,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Chaos Shock',
                        date: 'April 1, 2008',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Rovin Chase',
                        date: 'May 1, 2008',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Black Box',
                        date: 'June 1, 2008',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Room 501',
                        date: 'July 1, 2008',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Mosh Pit',
                        date: 'August 1, 2008',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'The Embossing Process',
                        date: 'September 1, 2008',
                        pages: 22,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Cross-News',
                        date: 'November 1, 2008',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Idea Drome',
                        date: 'December 1, 2008',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Lucky ★ Jerk',
                        date: 'January 1, 2009',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Advance Level Magic',
                        date: 'February 1, 2009',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Headbump-Ballad',
                        date: 'April 1, 2009',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Q&A',
                        date: 'May 1, 2009',
                        pages: 32,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Eye Contact',
                        date: 'July 1, 2009',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => "A Demon's Dining Table",
                        date: 'August 1, 2009',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Headband Journey',
                        date: 'October 1, 2009',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Ground Zero',
                        date: 'November 1, 2009',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Killing Field',
                        date: 'December 1, 2009',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Morphing',
                        date: 'January 1, 2010',
                        pages: 32,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Placekicker',
                        date: 'March 1, 2010',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Messy Skull',
                        date: 'April 1, 2010',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Strange Love',
                        date: 'May 1, 2010',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Day Zero',
                        date: 'June 1, 2010',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Eyewitness',
                        date: 'July 1, 2010',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Evil Makeover',
                        date: 'September 1, 2010',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Whole in One',
                        date: 'October 1, 2010',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'Remaining Bullets',
                        date: 'November 1, 2010',
                        pages: 26,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Cross Replay',
                        date: 'January 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Conceptual Quarrel',
                        date: 'February 1, 2011',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Free Hospital',
                        date: 'March 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => "Fujita's Excellent Adventure",
                        date: 'April 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Morphing',
                        date: 'June 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Playing with Parts',
                        date: 'August 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Half-Clear',
                        date: 'September 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Colorless Hero',
                        date: 'October 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Venture Junction',
                        date: 'December 1, 2011',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Bug Harassment',
                        date: 'January 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Silent Reunion',
                        date: 'February 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Food Court Full-Course Meal',
                        date: 'May 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Quagmire',
                        date: 'June 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Sludge Sacrifice',
                        date: 'July 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Mirage Landmark',
                        date: 'August 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Seriously Close',
                        date: 'September 1, 2012',
                        pages: 26,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Revival Bluff',
                        date: 'November 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Castle on the Lake',
                        date: 'December 1, 2012',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Deep House',
                        date: 'January 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Blind Labyrinth',
                        date: 'February 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Wired Dead',
                        date: 'March 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Cracking Tube',
                        date: 'April 1, 2013',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => "Smash 'n' Grab",
                        date: 'May 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Decentralized Department Store',
                        date: 'June 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Reunion',
                        date: 'August 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Evil Day Trip',
                        date: 'September 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Biological Renovation',
                        date: 'October 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => "Haru's Gym Class",
                        date: 'November 1, 2013',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Pit of the Stomach',
                        date: 'January 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Rolling Heads',
                        date: 'February 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => "Evil's Tail",
                        date: 'March 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Rare Body Parts',
                        date: 'April 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Free Play',
                        date: 'May 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Return of the Cycle of Life',
                        date: 'June 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Last-Ditch Resurrection',
                        date: 'August 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Speculative Hole',
                        date: 'September 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Extortion Completed',
                        date: 'October 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Control vs. Control',
                        date: 'November 1, 2014',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Lock Out & Disperse',
                        date: 'April 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Black Town',
                        date: 'May 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Swearing to the Remains',
                        date: 'June 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => "The Devil's Gyoza",
                        date: 'July 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Crazy Comeback',
                        date: 'August 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Maze Trail',
                        date: 'September 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Crazy Dystopia',
                        date: 'November 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Fusion Setup',
                        date: 'December 1, 2015',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Devil Gambling',
                        date: 'January 1, 2016',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Sacrificial Wish',
                        date: 'March 1, 2016',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Extreme Mushroom Critical',
                        date: 'April 1, 2016',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Birthday',
                        date: 'May 1, 2016',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Expansion Limit',
                        date: 'June 1, 2016',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'The Source of Evil',
                        date: 'July 1, 2016',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Sayonara full swing',
                        date: 'August 1, 2016',
                        pages: 30,
                        cover: null,
                    },
                    {
                        title: () => 'Long Desired Birthday',
                        date: 'September 1, 2016',
                        pages: 36,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Infernal Friend',
                        date: 'November 1, 2016',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Inside of Inside of Inside is na-na-na',
                        date: 'December 1, 2016',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'Hole Gourmet Report',
                        date: 'January 1, 2017',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Extra Dimensional Dream',
                        date: 'February 1, 2017',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Future Forecast: Heavy Rain',
                        date: 'March 1, 2017',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => "Hole-Kun's Counting Song",
                        date: 'April 1, 2017',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'The sound of parting rain',
                        date: 'May 1, 2017',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'I am Kaiman',
                        date: 'June 1, 2017',
                        pages: 50,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Offense and Defense Inside The Mushroom',
                        date: 'August 1, 2017',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Magic as Gyou wish',
                        date: 'December 1, 2017',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => "Shou's Revival Show",
                        date: 'January 1, 2018',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'A Happy Reunion',
                        date: 'February 1, 2018',
                        pages: 26,
                        cover: null,
                    },
                    {
                        title: () => 'The Abyss and the Mountain',
                        date: 'March 1, 2018',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Eternal Grudge',
                        date: 'April 1, 2018',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'A Shocking Face',
                        date: 'May 1, 2018',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Rolling Head',
                        date: 'June 1, 2018',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: () => 'Gyoza Barrage',
                        date: 'July 1, 2018',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Dorohedoro',
                        date: 'August 1, 2018',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'Final Battle',
                        date: 'September 1, 2018',
                        pages: 32,
                        cover: null,
                    },
                    {
                        title: () => 'All-Star Sayonara',
                        date: 'October 1, 2018',
                        pages: 33,
                        cover: null,
                    },
                ],
            },
        ] as const satisfies Tuple<Volume, VolumesTotal>,
        seasons: [
            {
                title: 'Dorohedoro - Season 1',
                cover: seasonCover,
                offset: { x: 0, y: 500 },
                chapters: { from: 1, to: 41 },
                episodes: [
                    {
                        title: 'Kaiman',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'January 13, 2020',
                        chapters: { from: 1, to: 4 },
                    },
                    {
                        title: 'In the Bag',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'January 20, 2020',
                        chapters: { from: 4, to: 7 },
                    },
                    {
                        title: 'Night of the Dead - Duel! - In Front of the Main Department Store',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'January 27, 2020',
                        chapters: { from: 7, to: 9 },
                    },
                    {
                        title: 'Roast Duck à La Sorcerer',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'February 3, 2020',
                        chapters: { from: 9, to: 13 },
                    },
                    {
                        title: 'Kaiman in Wonderland',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'February 10, 2020',
                        chapters: { from: 14, to: 16 },
                    },
                    {
                        title: 'The Mushrooms Are Ready',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'February 17, 2020',
                        chapters: { from: 17, to: 19 },
                    },
                    {
                        title: 'The All-Star ☆ Dream Game',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'February 24, 2020',
                        chapters: { from: 20, to: 23 },
                    },
                    {
                        title: 'A Good Day To Leave',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'March 2, 2020',
                        chapters: { from: 23, to: 26 },
                    },
                    {
                        title: 'Oh, Flower Smoke',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'March 9, 2020',
                        chapters: { from: 27, to: 30 },
                    },
                    {
                        title: 'Lonely Kaiman',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'March 16, 2020',
                        chapters: { from: 30, to: 35 },
                    },
                    {
                        title: "Let's Meet At The Food Stall",
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'March 23, 2020',
                        chapters: { from: 35, to: 38 },
                    },
                    {
                        title: 'Memories Of School Days',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'March 30, 2020',
                        chapters: { from: 39, to: 41 },
                    },
                ],
            },
            {
                title: 'Dorohedoro - Season 2',
                cover: seasonCover,
                offset: { x: 0, y: 1000 },
                chapters: { from: 42, to: 73 },
                episodes: [],
            },
            { chapters: { from: 74, to: 120 } },
            { chapters: { from: 121, to: 167 } },
        ] as const satisfies Tuple<Season, SeasonsTotal>,
        splitChapters: {
            4: 3,
            7: 2,
            9: 24,
            23: 3,
            30: 14,
            35: 14,
        },
        wikiBase: 'https://dorohedoro.fandom.com/wiki/',
        icons: {
            favicon: 'circle',
            scroller: ArrowRangeIcon,
            'select-title': ListIcon,
            'read-info': InfoIcon,
            'toggle-unbound-chapter-width': ExpandIcon,
            'toggle-cross-lines': FitIcon,
            'open-chapter-calendar': CalendarIcon,
            'toggle-always-show-titles': TitleIcon,
            'capture-timeline': CameraIcon,
        },
        socialLinks: [
            {
                name: 'Official Site',
                url: 'https://dorohedoro.net/',
            },
            {
                name: 'Official Twitter',
                url: 'https://twitter.com/dorohedoro_PR',
            },
        ],
    },
};
