/* eslint-disable max-lines */ // a lot of data for a title
import { Tuple } from '@shared/lib/util';
import {
    ArrowRangeIcon,
    CalendarIcon,
    CameraIcon,
    EmptyIcon,
    ExpandIcon,
    FitIcon,
    InfoIcon,
    ListIcon,
    TitleIcon,
} from '@shared/ui/icons';
import { Arc, Season, Timeline, Volume } from '@timelines/types';

const SEASON_HEIGHT = 942;
const EPISODE_HEIGHT = SEASON_HEIGHT * 0.25;
const VOLUME_HEIGHT = 1379;
const CHAPTER_HEIGHT = 100;
const ARC_HEIGHT = VOLUME_HEIGHT * 0.8;

type VolumesTotal = 31;
type ArcsTotal = 9;
type SeasonsTotal = 5;

// 0-based
const volumeCover = (n: number) => `Volume_${n - 1}`;
const chapterNumber = (n: number): string =>
    n <= 4 ? `0-${n}` : (n - 4).toString();

export const JJK_TIMELINE: Timeline = {
    layout: {
        season: {
            type: 'season',
            height: SEASON_HEIGHT,
            blankfontSize: 250,
            titleFontSize: 100,
            numberProcessor: n => (n - 1).toString(),
            sectionLink: 'Jujutsu Kaisen (Anime)',
            wikiLink: title => title,
            subTimeline: {
                type: 'episode',
                height: EPISODE_HEIGHT,
                scale: 1.2,
                titleProcessor: (title, n) => `${title}\n(Episode ${n})`,
                blankfontSize: 42,
                titleFontSize: 42,
                sectionLink: 'Jujutsu_Kaisen_(Anime)#Episodes',
                wikiLink: (_, n) => `Episode_${n}`,
                focusable: true,
            },
        },
        arc: {
            type: 'arc',
            height: ARC_HEIGHT,
            titleProcessor: title => `${title} Arc`,
            blankfontSize: 100,
            titleFontSize: 100,
            sectionLink: 'Story Arcs',
            wikiLink: title => title,
        },
        timeline: {
            type: 'timeline',
        },
        chapter: {
            type: 'chapter',
            height: CHAPTER_HEIGHT,
            fit: 'contain',
            backgroundColor: 'white',
            numberProcessor: chapterNumber,
            blankfontSize: 45,
            titleFontSize: 45,
            sectionLink: 'Volumes & Chapters',
            wikiLink: (_, n) => `Chapter_${chapterNumber(n)}`,
            focusable: true,
        },
        volume: {
            type: 'volume',
            height: VOLUME_HEIGHT,
            defaultCoverPosition: 'top',
            titleProcessor: (title, n) => `${title}\n(Volume ${n - 1})`,
            blankfontSize: 500,
            titleFontSize: 100,
            sectionLink: 'Volumes & Chapters',
            wikiLink: (_, n) => `Volume_${n - 1}`,
        },
    },
    data: {
        title: 'Jujutsu Kaisen',
        volumes: [
            {
                title: () => 'Blinding Darkness',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Cursed Child',
                        date: 'April 28, 2017',
                        pages: 52,
                        cover: null,
                    },
                    {
                        title: () => 'Blacker and Blacker',
                        date: 'May 26, 2017',
                        pages: 45,
                        cover: null,
                    },
                    {
                        title: () => 'Punishment for the Weak',
                        date: 'June 23, 2017',
                        pages: 45,
                        cover: null,
                    },
                    {
                        title: () => 'Bright Darkness',
                        date: 'July 28, 2017',
                        pages: 47,
                        cover: null,
                    },
                ],
            },
            {
                title: 1,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Ryomen Sukuna',
                        date: 'March 5, 2018',
                        pages: 55,
                        cover: null,
                    },
                    {
                        title: () => 'Secret Execution',
                        date: 'March 12, 2018',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: () => 'For Myself',
                        date: 'March 19, 2018',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Girl of Steel',
                        date: 'March 26, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Start',
                        date: 'April 2, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome Womb',
                        date: 'April 9, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome Womb, Part 2',
                        date: 'April 16, 2018',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Fearsome Womb',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Fearsome Womb, Part 3',
                        date: 'April 23, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome Womb, Part 4',
                        date: 'May 2, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'After the Rain',
                        date: 'May 14, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'A Dream',
                        date: 'May 21, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Pushing Forward',
                        date: 'May 28, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Watching Movies',
                        date: 'June 4, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Assault',
                        date: 'June 11, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Domain',
                        date: 'June 18, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Affection',
                        date: 'June 25, 2018',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: 3,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Boredom',
                        date: 'July 2, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Bottom',
                        date: 'July 9, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Young Fish and Reverse Punishment',
                        date: 'July 16, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Young Fish and Reverse Punishment, Part 2',
                        date: 'July 23, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Young Fish and Reverse Punishment, Part 3',
                        date: 'July 30, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Young Fish and Reverse Punishment, Part 4',
                        date: 'August 6, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Young Fish and Reverse Punishment, Part 5',
                        date: 'August 20, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Young Fish and Revere Punishment, Part 6',
                        date: 'August 27, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Narrow Minded',
                        date: 'September 3, 2018',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 3,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'To You Someday',
                        date: 'September 10, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'What If',
                        date: 'September 17, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => "I'm Gonna Kill You!",
                        date: 'September 22, 2018',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Growth',
                        date: 'October 1, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Selfishness',
                        date: 'October 8, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tomorrow',
                        date: 'October 15, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Introspection',
                        date: 'October 22, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 0',
                        date: 'October 29, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 1',
                        date: 'November 5, 2018',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Kyoto Sister School Goodwill Event',
                cover: volumeCover,
                chapters: [
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 2',
                        date: 'November 12, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 3',
                        date: 'November 19, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 4',
                        date: 'November 26, 2018',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 5',
                        date: 'December 3, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 6',
                        date: 'December 10, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister SchoolGoodwill Event - Team Battle, Part 7',
                        date: 'December 17, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 8',
                        date: 'December 22, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 9',
                        date: 'January 7, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 10',
                        date: 'January 21, 2019',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: 5,
                cover: volumeCover,
                chapters: [
                    {
                        title: () =>
                            'Kyoto Sister School Goodwill Event - Team Battle, Part 11',
                        date: 'January 28, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sage',
                        date: 'February 4, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Time',
                        date: 'February 9, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Cursed Tools',
                        date: 'February 18, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Black Flash',
                        date: 'February 25, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Constrained',
                        date: 'March 4, 2019',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Feeling',
                        date: 'March 11, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'A Flower Offering',
                        date: 'March 18, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Nonstandard',
                        date: 'March 25, 2019',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 3,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Completion',
                        date: 'April 1, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Jujutsu Koshien',
                        date: 'April 8, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience',
                        date: 'April 15, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience, Part 2',
                        date: 'April 22, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience, Part 3',
                        date: 'April 27, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience, Part 4',
                        date: 'May 13, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience, Part 5',
                        date: 'May 20, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience, Part 6',
                        date: 'May 27, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Origin of Obedience, Part 7',
                        date: 'June 3, 2019',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 4,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Origin of Obedience, Part 8',
                        date: 'June 10, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Accomplices',
                        date: 'June 17, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => "It's Like That",
                        date: 'June 24, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory',
                        date: 'July 1, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 2',
                        date: 'July 8, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 3',
                        date: 'July 13, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 4',
                        date: 'July 22, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 5',
                        date: 'July 29, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 6',
                        date: 'August 5, 2019',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: 6,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Hidden Inventory, Part 7',
                        date: 'August 19, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 8',
                        date: 'August 26, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 9',
                        date: 'September 2, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 10',
                        date: 'September 9, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Hidden Inventory, Part 11',
                        date: 'September 14, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Premature Death',
                        date: 'September 21, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Premature Death, Part 2',
                        date: 'September 30, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Premature Death, Part 3',
                        date: 'October 7, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'A Taste of Things to Come',
                        date: 'October 14, 2019',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: 1,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Evening Festival',
                        date: 'October 21, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Evening Festival, Part 2',
                        date: 'October 28, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Evening Festival, Part 3',
                        date: 'November 2, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 1',
                        date: 'November 11, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 2',
                        date: 'November 18, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 3',
                        date: 'November 25, 2019',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 4',
                        date: 'December 2, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 5',
                        date: 'December 9, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 6',
                        date: 'December 16, 2019',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'The Shibuya Incident ーGate Openー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Shibuya Incident, Part 7',
                        date: 'December 23, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 8',
                        date: 'January 3, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 9',
                        date: 'January 20, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 10',
                        date: 'January 27, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 11',
                        date: 'February 3, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 12',
                        date: 'February 10, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 13',
                        date: 'February 17, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 14',
                        date: 'February 22, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 15',
                        date: 'March 2, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'The Shibuya Incident ーSummonー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Shibuya Incident, Part 16',
                        date: 'March 9, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 17',
                        date: 'March 16, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 18',
                        date: 'March 23, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 19',
                        date: 'March 30, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 20',
                        date: 'April 6, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 21',
                        date: 'April 13, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 22',
                        date: 'April 27, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 23',
                        date: 'May 11, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 24',
                        date: 'May 18, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'The Shibuya Incident ーThunderclapー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Shibuya Incident, Part 25',
                        date: 'May 25, 2020',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 26',
                        date: 'June 1, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 27',
                        date: 'June 8, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 28',
                        date: 'June 15, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 29',
                        date: 'June 22, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 30',
                        date: 'June 27, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 31',
                        date: 'July 6, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 32',
                        date: 'July 13, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 33',
                        date: 'July 20, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'The Shibuya Incident ーRight and Wrongー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Shibuya Incident, Part 34',
                        date: 'August 3, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Shibuya Incident, Part 35',
                        date: 'August 11, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 118',
                        date: 'August 24, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 119',
                        date: 'August 31, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 120',
                        date: 'September 7, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 121',
                        date: 'September 14, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 122',
                        date: 'September 19, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 123',
                        date: 'September 28, 2020',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 124',
                        date: 'October 5, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'The Shibuya Incident ーTransformationー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Chapter 125',
                        date: 'October 12, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 126',
                        date: 'October 17, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 127',
                        date: 'October 26, 2020',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 128',
                        date: 'November 2, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 129',
                        date: 'November 9, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 130',
                        date: 'November 21, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 131',
                        date: 'November 30, 2020',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 132',
                        date: 'December 7, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 133',
                        date: 'December 21, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'The Shibuya Incident ーGate Closedー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Chapter 134',
                        date: 'January 4, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 135',
                        date: 'January 18, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 136',
                        date: 'January 25, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 137',
                        date: 'February 1, 2021',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 138',
                        date: 'February 15, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 139',
                        date: 'February 22, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 140',
                        date: 'March 1, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 141',
                        date: 'March 8, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Chapter 142',
                        date: 'March 15, 2021',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 6,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Chapter 143',
                        date: 'March 22, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'That Place',
                        date: 'March 28, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Back',
                        date: 'April 12, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'About the Culling Game',
                        date: 'April 19, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Even Pandas',
                        date: 'April 26, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Perfect Preparation',
                        date: 'May 17, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Perfect Preparation, Part 2',
                        date: 'May 24, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Perfect Preparation, Part 3',
                        date: 'May 31, 2021',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Perfect Preparation, Part 4',
                        date: 'June 7, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Perfect Preparation, Epilogue',
                        date: 'June 14, 2021',
                        pages: 9,
                        cover: null,
                    },
                ],
            },
            {
                title: 3,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Underground Fight Club',
                        date: 'August 2, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sneaking In',
                        date: 'August 10, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Fever',
                        date: 'August 23, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Twinkling Stars',
                        date: 'August 30, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Cog',
                        date: 'September 6, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Kogane',
                        date: 'September 13, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Judgment',
                        date: 'September 18, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Colony',
                        date: 'September 27, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 1',
                        date: 'October 4, 2021',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Tokyo No. 1 Colony ーAngry Manー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 2',
                        date: 'October 18, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 3',
                        date: 'October 25, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 4',
                        date: 'November 8, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 5',
                        date: 'November 15, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 6',
                        date: 'November 22, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 7',
                        date: 'December 6, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 8',
                        date: 'December 13, 2021',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 9',
                        date: 'December 20, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 10',
                        date: 'January 4, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 11',
                        date: 'January 17, 2022',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Sendai Colony ーThe Height of the Feastー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 12',
                        date: 'January 24, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 1 Colony, Part 13',
                        date: 'January 31, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 1',
                        date: 'February 7, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 2',
                        date: 'February 21, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 3',
                        date: 'February 28, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 4',
                        date: 'March 7, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 5',
                        date: 'March 19, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 6',
                        date: 'March 28, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sendai Colony, Part 7',
                        date: 'April 4, 2022',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Tokyo No. 2 Colony ーIncredible Luckー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 1',
                        date: 'April 18, 2022',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 2',
                        date: 'April 25, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 3',
                        date: 'May 9, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 4',
                        date: 'May 16, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Bye-bye',
                        date: 'May 23, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 5',
                        date: 'May 30, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 6',
                        date: 'June 13, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 7',
                        date: 'June 20, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 8',
                        date: 'June 27, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Tokyo No. 2 Colony, Part 9',
                        date: 'July 11, 2022',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Sakurajima Colony ーRebirthー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Sakurajima Colony, Part 1',
                        date: 'July 19, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 2',
                        date: 'August 1, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 3',
                        date: 'August 8, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 4',
                        date: 'August 22, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 5',
                        date: 'August 29, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 6',
                        date: 'September 5, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 7',
                        date: 'September 12, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Sakurajima Colony, Part 8',
                        date: 'September 26, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Resentful Names',
                        date: 'October 3, 2022',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 6,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Direct Talks, Part 1',
                        date: 'October 11, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Direct Talks, Part 2',
                        date: 'October 17, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Blood and Oil',
                        date: 'October 31, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Blood and Oil, Part 2',
                        date: 'November 7, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Blood and Oil, Part 3',
                        date: 'November 14, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Stars and Oil',
                        date: 'November 28, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Stars and Oil, Part 2',
                        date: 'December 5, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Stars and Oil, Part 3',
                        date: 'December 19, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Stars and Oil, Part 4',
                        date: 'December 26, 2022',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Fearsome Womb ーRecurrenceー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Offering to the Unknown',
                        date: 'January 7, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Offering to the Unknown, Part 2',
                        date: 'January 23, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Ripening',
                        date: 'January 30, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Ripening, Part 2',
                        date: 'February 6, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome Womb, Part 5',
                        date: 'February 13, 2023',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome Womb, Part 6',
                        date: 'February 27, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Fearsome Womb, Part 7',
                        date: 'March 6, 2023',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Bath',
                        date: 'March 13, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Bath, Part 2',
                        date: 'March 20, 2023',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Inhuman Makyo Shinjuku Showdown',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Bath, Part 3',
                        date: 'April 3, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Bath, Part 4',
                        date: 'April 10, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Self-Purification, Self-Constraint',
                        date: 'April 17, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Gain and Loss',
                        date: 'April 24, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Foretokens',
                        date: 'May 15, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 1',
                        date: 'May 22, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 2',
                        date: 'May 29, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 3',
                        date: 'June 12, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 4',
                        date: 'June 19, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 5',
                        date: 'July 3, 2023',
                        pages: 22,
                        cover: null,
                    },
                ],
            },
            {
                title: 9,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 6',
                        date: 'July 10, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 7',
                        date: 'July 17, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 8',
                        date: 'July 31, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 9',
                        date: 'August 7, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 10',
                        date: 'August 21, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 11',
                        date: 'August 28, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 12',
                        date: 'September 4, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 13',
                        date: 'September 11, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Heading South',
                        date: 'September 25, 2023',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 3,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 14',
                        date: 'October 2, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 15',
                        date: 'October 9, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Foolish Survivor!!',
                        date: 'October 23, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Foolish Survivor—Live On—',
                        date: 'October 30, 2023',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Foolish Survivor—Win and Remain—',
                        date: 'November 6, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Foolish Survivor—Flying High—',
                        date: 'November 20, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Foolish Survivor—Laughing It Up—',
                        date: 'November 27, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 16',
                        date: 'December 4, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 17',
                        date: 'December 18, 2023',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () => 'Inhuman Makyo Shinjuku Showdown ーSeimokuー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 18',
                        date: 'December 25, 2023',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 19',
                        date: 'January 6, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 20',
                        date: 'January 22, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 21',
                        date: 'February 5, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 22',
                        date: 'February 12, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 23',
                        date: 'February 19, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 24',
                        date: 'March 4, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 25',
                        date: 'March 11, 2024',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 26',
                        date: 'March 25, 2024',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: () =>
                    'Inhuman Makyo Shinjuku Showdown ーLife and Deathー',
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 27',
                        date: 'April 1, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 28',
                        date: 'April 8, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 29',
                        date: 'April 22, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 30',
                        date: 'April 29, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 31',
                        date: 'May 13, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 32',
                        date: 'May 20, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 33',
                        date: 'May 27, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 34',
                        date: 'June 10, 2024',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 35',
                        date: 'July 15, 2024',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: 8,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 36',
                        date: 'July 29, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'That Day',
                        date: 'August 5, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 37',
                        date: 'August 19, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Inhuman Makyo Shinjuku Showdown, Part 38',
                        date: 'August 26, 2024',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Settling Matters',
                        date: 'September 2, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Considerations',
                        date: 'September 16, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The End of the Dream',
                        date: 'September 23, 2024',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'From Now On',
                        date: 'September 30, 2024',
                        pages: 22,
                        cover: null,
                    },
                ],
            },
        ] as const satisfies Tuple<Volume, VolumesTotal>,
        arcs: [
            {
                title: 'Cursed Child',
                cover: 'Chapter_0-1_clear',
                offset: { x: 350, y: 0 },
                chapters: { from: 1, to: 4 },
            },
            {
                title: 'Fearsome Womb',
                cover: 'Chapter_1_(Cleaned)',
                offset: { x: 0, y: 100 },
                chapters: { from: 4 + 1, to: 4 + 18 },
            },
            {
                title: 'Vs. Mahito',
                cover: 'Anime_Key_Visual_6',
                offset: { x: 0, y: 440 },
                chapters: { from: 4 + 19, to: 4 + 31 },
            },
            {
                title: 'Kyoto Goodwill Event',
                cover: 'Anime_Key_Visual_4_(Cleaned)',
                offset: { x: 0, y: 500 },
                chapters: { from: 4 + 32, to: 4 + 54 },
            },
            {
                title: 'Death Painting',
                cover: 'Chapter_58_(Cleaned)',
                offset: { x: 0, y: 0 },
                chapters: { from: 4 + 55, to: 4 + 64 },
            },
            {
                title: "Gojo's Past",
                cover: 'Anime_Key_Visual_11',
                offset: { x: 0, y: 810 },
                chapters: { from: 4 + 65, to: 4 + 79 },
            },
            {
                title: 'Shibuya Incident',
                cover: 'Chapter_107',
                offset: { x: 0, y: 0 },
                chapters: { from: 4 + 80, to: 4 + 137 },
            },
            {
                title: 'Culling Game',
                cover: 'Jump_Festa_2022_Genga_Museum_illustration',
                offset: { x: 0, y: 2900 },
                chapters: { from: 4 + 138, to: 4 + 221 },
            },
            {
                title: 'Shinjuku Showdown',
                cover: 'Chapter_246_(Cleaned)',
                offset: { x: 0, y: 4370 },
                chapters: { from: 4 + 222 },
            },
        ] as const satisfies Tuple<Arc, ArcsTotal>,
        seasons: [
            {
                title: 'Jujutsu Kaisen 0: The Movie',
                cover: () => 'Jujutsu_Kaisen_Movie_Key_Visual_2_(Cleaned)',
                offset: { x: 0, y: 0 },
                chapters: { from: 1, to: 4 },
                episodes: [],
            },
            {
                title: 'Jujutsu Kaisen (Anime)',
                cover: () => 'Anime_Key_Visual_2',
                offset: { x: 0, y: 2620 },
                chapters: { from: 4 + 1, to: 4 + 63 },
                episodes: [
                    {
                        title: 'Ryomen Sukuna',
                        cover: () => 'The_Curse_known_as_Yuji_Itadori_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 3, 2020',
                        chapters: { from: 4 + 1, to: 4 + 2 },
                    },
                    {
                        title: 'For Myself',
                        cover: () => 'For_Myself_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 10, 2020',
                        chapters: { from: 4 + 2, to: 4 + 3 },
                    },
                    {
                        title: 'Girl of Steel',
                        cover: () => "Nobara's_Hammer_and_Nails_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'October 17, 2020',
                        chapters: { from: 4 + 4, to: 4 + 5 },
                    },
                    {
                        title: 'Fearsome Womb',
                        cover: () =>
                            'Special_Grade_Curse_suprises_Yuji_and_Megumi_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 24, 2020',
                        chapters: { from: 4 + 6, to: 4 + 8 },
                    },
                    {
                        title: 'Fearsome Womb, Part 2',
                        cover: () => 'Sukuna_glares_at_Megumi_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 31, 2020',
                        chapters: { from: 4 + 8, to: 4 + 10 },
                    },
                    {
                        title: 'After the Rain',
                        cover: () =>
                            'Jogo_claims_he_will_kill_Satoru_Gojo_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 7, 2020',
                        chapters: { from: 4 + 10, to: 4 + 13 },
                    },
                    {
                        title: 'Assault',
                        cover: () =>
                            'Gojo_shows_Jogo_the_difference_in_strength_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 14, 2020',
                        chapters: { from: 4 + 13, to: 4 + 16 },
                    },
                    {
                        title: 'Boring',
                        cover: () => 'Aoi_gets_excited_to_test_Megumi_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 21, 2020',
                        chapters: { from: 4 + 16, to: 4 + 18 },
                    },
                    {
                        title: 'Young Fish and Reverse Punishment',
                        cover: () => 'Mahito_reading_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 28, 2020',
                        chapters: { from: 4 + 19, to: 4 + 21 },
                    },
                    {
                        title: 'Idle Transfiguration',
                        cover: () => 'Mahito_explaining_the_soul_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'December 5, 2020',
                        chapters: { from: 4 + 21, to: 4 + 23 },
                    },
                    {
                        title: 'Narrow-Minded',
                        cover: () => 'Junpei_and_his_shikigami_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'December 12, 2020',
                        chapters: { from: 4 + 23, to: 4 + 25 },
                    },
                    {
                        title: 'To You Someday',
                        cover: () =>
                            "Yuji's_fantasy_of_Junpei_as_a_jujutsu_student_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'December 19, 2020',
                        chapters: { from: 4 + 26, to: 4 + 29 },
                    },
                    {
                        title: 'Tomorrow',
                        cover: () => 'Yuji_swears_not_to_lose_again_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'December 26, 2020',
                        chapters: { from: 4 + 29, to: 4 + 31 },
                    },
                    {
                        title: 'Kyoto Sister School Goodwill Event - Team Battle, Part 0',
                        cover: () =>
                            'Noritoshi_tells_his_team_to_attack_Yuji_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 16, 2021',
                        chapters: { from: 4 + 32, to: 4 + 33 },
                    },
                    {
                        title: 'Kyoto Sister School Goodwill Event - Team Battle, Part 1',
                        cover: () =>
                            "Aoi_Todo's_fantasy_memories_with_Yuji_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'January 23, 2021',
                        chapters: { from: 4 + 34, to: 4 + 36 },
                    },
                    {
                        title: 'Kyoto Sister School Goodwill Event - Team Battle, Part 2',
                        cover: () =>
                            'Gorilla_Mode_ready_to_finish_Mechamaru_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 30, 2021',
                        chapters: { from: 4 + 37, to: 4 + 39 },
                    },
                    {
                        title: 'Kyoto Sister School Goodwill Event - Team Battle, Part 3',
                        cover: () => 'Maki_crashing_into_a_stream_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'February 6, 2021',
                        chapters: { from: 4 + 40, to: 4 + 42 },
                    },
                    {
                        title: 'Sage',
                        cover: () => "Hanami's_intentions_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'February 13, 2021',
                        chapters: { from: 4 + 43, to: 4 + 46 },
                    },
                    {
                        title: 'Black Flash',
                        cover: () =>
                            'Yuji_after_hitting_Hanami_with_Black_Flash_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'February 20, 2021',
                        chapters: { from: 4 + 46, to: 4 + 49 },
                    },
                    {
                        title: 'Nonstandard',
                        cover: () =>
                            'Satoru_Gojo_smirks_before_attacking_Juzo_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'February 27, 2021',
                        chapters: { from: 4 + 50, to: 4 + 52 },
                    },
                    {
                        title: 'Jujutsu Koshien',
                        cover: () => 'Yuji_hitting_a_home_run_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'March 6, 2021',
                        chapters: { from: 4 + 53, to: 4 + 54 },
                    },
                    {
                        title: 'The Origin of Obedience',
                        cover: () =>
                            'Yuji,_Megumi,_and_Nobara_head_inside_the_barrier_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'March 13, 2021',
                        chapters: { from: 4 + 55, to: 4 + 56 },
                    },
                    {
                        title: 'The Origin of Obedience, Part 2',
                        cover: () => 'Megumi_after_casting_his_Domain_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'March 20, 2021',
                        chapters: { from: 4 + 57, to: 4 + 59 },
                    },
                    {
                        title: 'Accomplices',
                        cover: () =>
                            'Nobara_using_Resonance_to_stun_Eso_and_Kechizu_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'March 27, 2021',
                        chapters: { from: 4 + 60, to: 4 + 63 },
                    },
                ],
            },
            {
                title: 'Jujutsu Kaisen (Anime)',
                cover: () => 'Anime_Key_Visual_12',
                offset: { x: 0, y: 4580 },
                chapters: { from: 4 + 64, to: 4 + 139 },
                episodes: [
                    {
                        title: 'Hidden Inventory',
                        cover: () => 'Satoru_provokes_Suguru_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'July 6, 2023',
                        chapters: { from: 4 + 64, to: 4 + 66 },
                    },
                    {
                        title: 'Hidden Inventory, Part 2',
                        cover: () =>
                            'Riko_fearless_to_assimilate_into_Tengen_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'July 13, 2023',
                        chapters: { from: 4 + 67, to: 4 + 69 },
                    },
                    {
                        title: 'Hidden Inventory, Part 3',
                        cover: () => 'Toji_shows_himself_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'July 20, 2023',
                        chapters: { from: 4 + 70, to: 4 + 72 },
                    },
                    {
                        title: 'Hidden Inventory, Part 4',
                        cover: () => 'Satoru_high_on_his_awakening_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'July 27, 2023',
                        chapters: { from: 4 + 73, to: 4 + 76 },
                    },
                    {
                        title: 'Premature Death',
                        cover: () => 'Suguru_begins_to_lose_his_way_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'August 3, 2023',
                        chapters: { from: 4 + 76, to: 4 + 79 },
                    },
                    {
                        title: "It's Like That",
                        cover: () => 'Yuko_approaches_Nobara_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'August 31, 2023',
                        chapters: { from: 4 + 79, to: 4 + 80 },
                    },
                    {
                        title: 'Evening Festival',
                        cover: () =>
                            "Kokichi's_last_ditch_attempt_at_victory_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'September 7, 2023',
                        chapters: { from: 4 + 80, to: 4 + 83 },
                    },
                    {
                        title: 'The Shibuya Incident',
                        cover: () => 'Yuji_faces_the_Grasshopper_Curse_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'September 14, 2023',
                        chapters: { from: 4 + 83, to: 4 + 88 },
                    },
                    {
                        title: 'The Shibuya Incident - Gate Open',
                        cover: () =>
                            'Satoru_Gojo_activates_his_Domain_in_Shibuya_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'September 21, 2023',
                        chapters: { from: 4 + 88, to: 4 + 91 },
                    },
                    {
                        title: 'Pandemonium',
                        cover: () =>
                            'Mahito_makes_a_game_out_of_hunting_Yuji_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'September 28, 2023',
                        chapters: { from: 4 + 91, to: 4 + 93 },
                    },
                    {
                        title: 'Summon',
                        cover: () => 'Ogami_reviving_Toji_Zenin_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 5, 2023',
                        chapters: { from: 4 + 94, to: 4 + 97 },
                    },
                    {
                        title: 'Dull Knife',
                        cover: () =>
                            'Nanami_wraps_his_tie_around_his_hand_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 12, 2023',
                        chapters: { from: 4 + 98, to: 4 + 101 },
                    },
                    {
                        title: 'Red Scale',
                        cover: () => 'Choso_gains_a_new_memory_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'October 19, 2023',
                        chapters: { from: 4 + 101, to: 4 + 106 },
                    },
                    {
                        title: 'Fluctuations',
                        cover: () => "Dagon_enraged_by_Hanami's_death_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'October 26, 2023',
                        chapters: { from: 4 + 106, to: 4 + 109 },
                    },
                    {
                        title: 'Fluctuations, Part 2',
                        cover: () => 'Toji_gleefully_fighting_Dagon_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 2, 2023',
                        chapters: { from: 4 + 110, to: 4 + 112 },
                    },
                    {
                        title: 'Thunderclap',
                        cover: () => 'Jogo_cries_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 9, 2023',
                        chapters: { from: 4 + 113, to: 4 + 116 },
                    },
                    {
                        title: 'Thunderclap, Part 2',
                        cover: () => 'Yuji_enters_a_cold_focused_state_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 16, 2023',
                        chapters: { from: 4 + 117, to: 4 + 120 },
                    },
                    {
                        title: 'Right and Wrong',
                        cover: () => "Nanami's_smile_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'November 23, 2023',
                        chapters: { from: 4 + 120, to: 4 + 122 },
                    },
                    {
                        title: 'Right and Wrong, Part 2',
                        cover: () => 'Nobara_realises_the_end_is_near_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'November 30, 2023',
                        chapters: { from: 4 + 123, to: 4 + 125 },
                    },
                    {
                        title: 'Right and Wrong, Part 3',
                        cover: () => 'Aoi_Todo_arrives_to_rescue_Yuji_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'December 7, 2023',
                        chapters: { from: 4 + 126, to: 4 + 128 },
                    },
                    {
                        title: 'Transformation',
                        cover: () => "Mahito's_Birthday_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'December 14, 2023',
                        chapters: { from: 4 + 129, to: 4 + 132 },
                    },
                    {
                        title: 'Transformation, Part 2',
                        cover: () =>
                            'Pseudo-Geto_asks_Yuji_to_discuss_the_future_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'December 21, 2023',
                        chapters: { from: 4 + 133, to: 4 + 135 },
                    },
                    {
                        title: 'The Shibuya Incident - Gate Closed',
                        cover: () =>
                            'Yuta_declares_he_will_kill_Yuji_Itadori_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'December 28, 2023',
                        chapters: { from: 4 + 136, to: 4 + 139 },
                    },
                ],
            },
            {
                title: 'Jujutsu Kaisen (Anime)',
                cover: () => 'Anime_Key_Visual_20',
                offset: { x: 0, y: 5030 },
                chapters: { from: 4 + 139, to: 4 + 220 },
                episodes: [
                    {
                        title: 'Execution',
                        cover: () => "Yuji_holds_back_Yuta's_Blade_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'January 9, 2026',
                        chapters: { from: 4 + 139, to: 4 + 141 },
                    },
                    {
                        title: 'One More Time',
                        cover: () => 'Megumi_asks_Yuji_to_save_him_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 9, 2026',
                        chapters: { from: 4 + 141, to: 4 + 144 },
                    },
                    {
                        title: 'About the Culling Game',
                        cover: () =>
                            'Tengen_reveals_the_back_of_Prison_Realm_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 16, 2026',
                        chapters: { from: 4 + 145, to: 4 + 146 },
                    },
                    {
                        title: 'Perfect Preparation',
                        cover: () => 'Maki_mourning_her_sister_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 23, 2026',
                        chapters: { from: 4 + 148, to: 4 + 152 },
                    },
                    {
                        title: 'Fever',
                        cover: () => 'Yuji_clashes_with_Hakari_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 30, 2026',
                        chapters: { from: 4 + 147, to: 4 + 155 },
                    },
                    {
                        title: 'Cog',
                        cover: () => 'Hakari_agrees_to_help_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'February 6, 2026',
                        chapters: { from: 4 + 155, to: 4 + 158 },
                    },
                    {
                        title: 'Tokyo No. 1 Colony, Part 1',
                        cover: () =>
                            "Rin_and_Remi_reveal_Higuruma's_location_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'February 13, 2026',
                        chapters: { from: 4 + 158, to: 4 + 162 },
                    },
                    {
                        title: 'Tokyo No. 1 Colony, Part 2',
                        cover: () => "Hiromi_listens_to_Yuji's_goal_(Anime)",
                        offset: { x: 0, y: 0 },
                        date: 'February 27, 2026',
                        chapters: { from: 4 + 162, to: 4 + 164 },
                    },
                    {
                        title: 'Tokyo No. 1 Colony, Part 3',
                        cover: () =>
                            'Yuji_confesses_to_mass_murder_in_Shibuya_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'March 6, 2026',
                        chapters: { from: 4 + 164, to: 4 + 167 },
                    },
                    {
                        title: 'Tokyo No. 1 Colony, Part 4',
                        cover: () => 'Takaba_teams_up_with_Megumi_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'March 13, 2026',
                        chapters: { from: 4 + 167, to: 4 + 170 },
                    },
                    {
                        title: 'Tokyo No. 1 Colony, Part 5',
                        cover: () => '',
                        offset: { x: 0, y: 0 },
                        date: 'March 20, 2026 ',
                        chapters: { from: 4 + 171, to: 4 + 174 },
                    },
                ],
            },
            { chapters: { from: 4 + 221 } },
        ] as const satisfies Tuple<Season, SeasonsTotal>,
        splitChapters: {
            [4 + 2]: 3,
            [4 + 8]: 16,
            [4 + 13]: 15,
            [4 + 16]: 14,
            [4 + 21]: 5,
            [4 + 23]: 11,
            [4 + 29]: 3,
            [4 + 46]: 4,
            [4 + 76]: 6,
            [4 + 79]: 8,
            [4 + 80]: 13,
            [4 + 83]: 9,
            [4 + 88]: 3,
            [4 + 91]: 2,
            [4 + 101]: 13,
            [4 + 106]: 7,
            [4 + 120]: 8,
            [4 + 139]: 3,
            [4 + 141]: 15,
            [4 + 155]: 14,
            [4 + 158]: 6,
            [4 + 162]: 17,
            [4 + 164]: 3,
            [4 + 167]: 4,
        },
        wikiBase: 'https://jujutsu-kaisen.fandom.com/wiki/',
        icons: {
            favicon: EmptyIcon,
            scroller: ArrowRangeIcon,
            'select-title': ListIcon,
            'read-info': InfoIcon,
            'toggle-unbound-chapter-width': ExpandIcon,
            'toggle-cross-lines': FitIcon,
            'open-chapter-calendar': CalendarIcon,
            'toggle-always-show-titles': TitleIcon,
            'capture-timeline': CameraIcon,
        },
        socialLinks: [],
    },
};
