/* eslint-disable max-lines */ // a lot of data for a title
import { pad, Tuple } from '@shared/lib/util';
import { Arc, Season, Timeline, Volume } from '@timelines/types';

const SEASON_HEIGHT = 1900;
const EPISODE_HEIGHT = SEASON_HEIGHT * 0.2;
const VOLUME_HEIGHT = 1571;
const CHAPTER_HEIGHT = 100;
const ARC_HEIGHT = VOLUME_HEIGHT * 0.8;

type VolumesTotal = 13;
type ArcsTotal = 4;
type SeasonsTotal = 3;

const volumeTitle = (n: number) => `Volume ${n}`;
const volumeCover = (n: number) => `Volume_${pad(n)}`;
const chapterTitle = (n: number) => `Chapter ${n}`;
const episodeCover = (n: number) => `Episode_${n}`;

export const JR_TIMELINE: Timeline = {
    layout: {
        season: {
            type: 'season',
            height: SEASON_HEIGHT,
            blankfontSize: 250,
            titleFontSize: 100,
            sectionLink: 'Jigokuraku (anime)',
            wikiLink: title => title,
            subTimeline: {
                type: 'episode',
                height: EPISODE_HEIGHT,
                scale: 1.2,
                titleProcessor: (title, n) => `${title}\n(Episode ${n})`,
                blankfontSize: 50,
                titleFontSize: 50,
                sectionLink: 'Jigokuraku_(anime)#Episodes',
                wikiLink: (_, n) => `Episode_${n}`,
                focusable: true,
            },
        },
        arc: {
            type: 'arc',
            height: ARC_HEIGHT,
            titleProcessor: title => `${title} Arc`,
            blankfontSize: 100,
            titleFontSize: 100,
            sectionLink: 'Story Arcs',
            wikiLink: title => title,
        },
        timeline: {
            type: 'timeline',
        },
        chapter: {
            type: 'chapter',
            height: CHAPTER_HEIGHT,
            fit: 'contain',
            backgroundColor: 'white',
            blankfontSize: 45,
            titleFontSize: 45,
            sectionLink: 'Chapters and Volumes',
            wikiLink: (_, n) => `Chapter_${n}`,
            focusable: true,
        },
        volume: {
            type: 'volume',
            height: VOLUME_HEIGHT,
            defaultCoverPosition: 'top',
            blankfontSize: 500,
            titleFontSize: 100,
            sectionLink: 'Chapters and Volumes',
            wikiLink: (_, n) => `Volume_${n}`,
        },
    },
    data: {
        title: 'Jigokuraku',
        volumes: [
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'January 22, 2018',
                        pages: 67,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 29, 2018',
                        pages: 55,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 5, 2018',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 12, 2018',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 19, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 26, 2018',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'March 5, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 12, 2018',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 19, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 26, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 2, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 9, 2018',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 16, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 23, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 30, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 7, 2018',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'May 21, 2018',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 28, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 4, 2018',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 11, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 18, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 25, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 9, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 16, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 23, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 30, 2018',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'August 13, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'August 27, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 3, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 10, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 24, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 1, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 8, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 15, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 22, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 29, 2018',
                        pages: 15,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'November 5, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 19, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 26, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 10, 2018',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 17, 2018',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 31, 2018',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 7, 2019',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 21, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 28, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 11, 2019',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'February 18, 2019',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 25, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 4, 2019',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 11, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 18, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 1, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 8, 2019',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 15, 2019',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 28, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 6, 2019',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'May 13, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 27, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 3, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 24, 2019',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 30, 2019',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 7, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 21, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 28, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 28, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'August 11, 2019',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'August 25, 2019',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 1, 2019',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 8, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 15, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 29, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 6, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 13, 2019',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 27, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 3, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 10, 2019',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'November 24, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 1, 2019',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 8, 2019',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 15, 2019',
                        pages: 25,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 29, 2019',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 6, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 13, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 19, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 26, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 9, 2020',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'February 16, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'February 23, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 8, 2020',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 15, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 20, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'March 29, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 5, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 19, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'April 26, 2020',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 3, 2020',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'May 10, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 17, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'May 31, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 7, 2020',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 14, 2020',
                        pages: 24,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 21, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'June 28, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 12, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 19, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'July 26, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'August 9, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'August 16, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'August 30, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 6, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 13, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 20, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'September 27, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 11, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 18, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'October 25, 2020',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: chapterTitle,
                        date: 'November 1, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 8, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 22, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'November 29, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 13, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 20, 2020',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'December 27, 2020',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 3, 2021',
                        pages: 23,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 11, 2021',
                        pages: 15,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 18, 2021',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: chapterTitle,
                        date: 'January 25, 2021',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
        ] as const satisfies Tuple<Volume, VolumesTotal>,
        arcs: [
            {
                title: 'Island',
                cover: 'The_vanguard_sailing_to_Kotaku',
                offset: { x: 0, y: 500 },
                chapters: { from: 1, to: 16 },
            },
            {
                title: 'Lord Tensen',
                cover: 'Lord_Tensen_Arc_Infobox',
                offset: { x: 0, y: 100 },
                chapters: { from: 17, to: 59 },
            },
            {
                title: 'Hōrai',
                cover: 'Horai_flower_setting',
                offset: { x: 0, y: 0 },
                chapters: { from: 60, to: 110 },
            },
            {
                title: 'Departure',
                cover: "The_Survivors_on_Rien's_ship",
                offset: { x: 0, y: 50 },
                chapters: { from: 111 },
            },
        ] as const satisfies Tuple<Arc, ArcsTotal>,
        seasons: [
            {
                title: 'Jigokuraku Season 1',
                cover: () => 'Jigokuraku_Key_Visual',
                offset: { x: 0, y: 2650 },
                chapters: { from: 1, to: 45 },
                episodes: [
                    {
                        title: 'The Death Row Convict and the Executioner',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'April 1, 2023',
                        chapters: { from: 1, to: 1 },
                    },
                    {
                        title: 'Screening and Choosing',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'April 8, 2023',
                        chapters: { from: 2, to: 2 },
                    },
                    {
                        title: 'Weakness and Strength',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'April 15, 2023',
                        chapters: { from: 3, to: 6 },
                    },
                    {
                        title: 'Hell and Paradise',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'April 22, 2023',
                        chapters: { from: 6, to: 9 },
                    },
                    {
                        title: 'The Samurai and the Woman',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'April 29, 2023',
                        chapters: { from: 10, to: 13 },
                    },
                    {
                        title: 'Heart and Reason',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'May 6, 2023',
                        chapters: { from: 13, to: 16 },
                    },
                    {
                        title: 'Flowers and Offerings',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'May 13, 2023',
                        chapters: { from: 16, to: 19 },
                    },
                    {
                        title: 'Student and Master',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'May 20, 2023',
                        chapters: { from: 19, to: 21 },
                    },
                    {
                        title: 'Gods and People',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'June 3, 2023',
                        chapters: { from: 21, to: 26 },
                    },
                    {
                        title: 'Yin and Yang',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'June 10, 2023',
                        chapters: { from: 27, to: 30 },
                    },
                    {
                        title: 'Weak and Strong',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'June 17, 2023',
                        chapters: { from: 30, to: 35 },
                    },
                    {
                        title: 'Umbrella and Ink',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'June 24, 2023',
                        chapters: { from: 35, to: 40 },
                    },
                    {
                        title: 'Dreams and Reality',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'July 1, 2023',
                        chapters: { from: 40, to: 45 },
                    },
                ],
            },
            {
                title: 'Jigokuraku Season 2',
                cover: () => 'Jigokuraku_Season_2_Key_Visual_2',
                offset: { x: 0, y: 3000 },
                chapters: { from: 45, to: 86 },
                episodes: [
                    {
                        title: 'Dawn and Confusion',
                        cover: () => 'Gabimaru_vs_Chobei_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 11, 2026',
                        chapters: { from: 45, to: 48 },
                    },
                    {
                        title: 'Reality and Fantasy',
                        cover: () => 'The_remaining_survivors_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 18, 2026',
                        chapters: { from: 49, to: 52 },
                    },
                    {
                        title: 'Immutability and Change',
                        cover: () => 'Rien_explaining_to_Chobei_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'January 25, 2026',
                        chapters: { from: 53, to: 56 },
                    },
                    {
                        title: 'The Samurai Code and Carnage',
                        cover: () => 'Shugen_angry_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'February 1, 2026',
                        chapters: { from: 57, to: 59 },
                    },
                    {
                        title: 'Humans and Sages',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'February 8, 2026',
                        chapters: { from: 60, to: 63 },
                    },
                    {
                        title: 'Hindering and Restoration',
                        cover: () => 'Gabimaru_and_Yuzuriha_vs_Ran_(Anime)',
                        offset: { x: 0, y: 0 },
                        date: 'February 15, 2026',
                        chapters: { from: 63, to: 67 },
                    },
                    {
                        title: 'Two People and One Person',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'February 22, 2026',
                        chapters: { from: 67, to: 74 },
                    },
                    {
                        title: 'Chrysanthemum and Peach',
                        cover: episodeCover,
                        offset: { x: 0, y: 0 },
                        date: 'March 1, 2026',
                        chapters: { from: 75, to: 77 },
                    },
                    {
                        title: 'Love and Karma',
                        cover: episodeCover,
                        offset: { x: 1, y: 0 },
                        date: 'March 8, 2026',
                        chapters: { from: 78, to: 81 },
                    },
                ],
            },
            { chapters: { from: 87 } },
        ] as const satisfies Tuple<Season, SeasonsTotal>,
        splitChapters: {
            6: 9,
            13: 3,
            16: 13,
            19: 7,
            21: 15,
            30: 20,
            40: 19,
            45: 9,
            63: 14,
            67: 22,
        },
        wikiBase: 'https://jigokuraku.fandom.com/wiki/',
        smallImages: {
            'scroller-or-favicon': 'circle',
            'read-info': 'circle',
            'toggle-unbound-chapter-width': 'circle',
            'toggle-cross-lines': 'circle',
            'open-chapter-calendar': 'circle',
            'toggle-always-show-titles': 'circle',
            'capture-timeline': 'circle',
        },
        socialLinks: [
            {
                name: 'Manga Plus',
                url: 'https://mangaplus.shueisha.co.jp/titles/100040',
            },
            {
                name: 'VIZ Media',
                url: 'https://www.viz.com/shonenjump/chapters/hells-paradise-jigokuraku',
            },
            { name: "Author's Twitter", url: 'https://x.com/ug_kaku' },
            {
                name: 'Shōnen Jump+',
                url: 'https://shonenjumpplus.com/episode/13932016480029295972',
            },
            {
                name: 'Official Anime Twitter',
                url: 'https://x.com/jplus_jigokurak',
            },
            { name: 'Anime Website', url: 'https://www.jigokuraku.com/' },
            {
                name: 'Crunchyroll',
                url: 'https://www.crunchyroll.com/series/GJ0H7Q5ZJ/hells-paradise',
            },
        ],
    },
};
