import { Tuple } from '../types';
import { Arc, Season, Timeline, TimelineData, Volume } from './';
import {
    getArcWidth,
    getChapterWidth,
    getEpisodeWidth,
    getSeasonWidth,
    getVolumeWidth,
} from './widthHelpers';

const SEASON_HEIGHT = 1000;
const EPISODE_HEIGHT = SEASON_HEIGHT * 0.33;
const VOLUME_HEIGHT = 1572;
const CHAPTER_HEIGHT = 100;
const ARC_HEIGHT = VOLUME_HEIGHT * 0.6;

const SEASONS_TOTAL = 3;
const ARCS_TOTAL = 10;
const VOLUMES_TOTAL = 15;

const volumeTitle = (_: TimelineData, idx: number) => `Volume ${idx + 1}`;
const volumeCover = (_: TimelineData, idx: number) => `Volume_${idx + 1}`;
const episodeCover = (_: TimelineData, idx: number) => `Episode_${idx + 1}`;

export const FRIEREN_TIMELINE: Timeline = {
    layout: {
        season: {
            type: 'season',
            height: SEASON_HEIGHT,
            blankfontSize: 250,
            titleFontSize: 100,
            width: getSeasonWidth,
            sectionLink: "Frieren: Beyond Journey's End (Anime)",
            wikiLink: title => title,
            subTimeline: {
                type: 'episode',
                height: EPISODE_HEIGHT,
                scale: 1.2,
                titleProcessor: (title, idx) => `${title}\n(Episode ${idx})`,
                blankfontSize: 42,
                titleFontSize: 38,
                width: getEpisodeWidth,
                sectionLink: "Frieren:_Beyond_Journey's_End_(Anime)#Episodes",
                wikiLink: (_, n) => `Episode_${n}`,
            },
        },
        arc: {
            type: 'arc',
            height: ARC_HEIGHT,
            sidewaysText: true,
            titleProcessor: title => `${title} arc`,
            blankfontSize: 100,
            titleFontSize: 100,
            width: getArcWidth,
            sectionLink: 'Story Arcs',
            wikiLink: title => `${title}_Arc`,
        },
        timeline: {
            type: 'timeline',
        },
        chapter: {
            type: 'chapter',
            height: CHAPTER_HEIGHT,
            fit: 'contain',
            backgroundColor: 'white',
            blankfontSize: 45,
            titleFontSize: 45,
            width: getChapterWidth,
            sectionLink: 'Chapters_and_Volumes#Volumes',
            wikiLink: (_, n) => `Chapter_${n}`,
            focusable: true,
        },
        volume: {
            type: 'volume',
            height: VOLUME_HEIGHT,
            blankfontSize: 500,
            titleFontSize: 100,
            width: getVolumeWidth,
            defaultCoverPosition: 'top',
            sectionLink: 'Chapters_and_Volumes#Volumes',
            wikiLink: (_, n) => `Volume_${n}`,
        },
    },
    data: {
        title: 'Frieren',
        volumes: [
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "The Journey's End",
                        date: 'April 28, 2020',
                        pages: 37,
                        cover: null,
                    },
                    {
                        title: () => "The Priest's Lie",
                        date: 'April 28, 2020',
                        pages: 34,
                        cover: null,
                    },
                    {
                        title: () => 'Blue-Moon Weed',
                        date: 'May 13, 2020',
                        pages: 34,
                        cover: null,
                    },
                    {
                        title: () => "The Mage's Secret",
                        date: 'May 20, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Killing Magic',
                        date: 'May 27, 2020',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => "New Year's Festival",
                        date: 'June 3, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Land Where Souls Rest',
                        date: 'June 17, 2020',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'One One-Hundredth',
                        date: 'June 24, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Phantoms of the Dead',
                        date: 'July 1, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Solar Dragon',
                        date: 'July 15, 2020',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'The Hero of the Village',
                        date: 'July 22, 2020',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'The Northern Checkpoint',
                        date: 'July 29, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Liberation Festival',
                        date: 'August 5, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Monsters That Speak',
                        date: 'August 19, 2020',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Draht',
                        date: 'August 26, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Murder of a Guard',
                        date: 'September 2, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Frieren the Slayer',
                        date: 'September 9, 2020',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Undead Army',
                        date: 'September 16, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Raid',
                        date: 'September 23, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => "Master's Technique",
                        date: 'September 30, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Coward',
                        date: 'October 7, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Scales of Obedience',
                        date: 'October 14, 2020',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'A Victory and a Funeral',
                        date: 'October 21, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => "The Elves' Wish",
                        date: 'October 28, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Village of the Sword',
                        date: 'November 4, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Gift to a Warrior',
                        date: 'November 11, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Priest from an Ordinary Village',
                        date: 'November 18, 2020',
                        pages: 19,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'The Priest and His Regret',
                        date: 'November 25, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Ideal Adult',
                        date: 'December 2, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Mirrored Lotus',
                        date: 'December 9, 2020',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Chaos Flower',
                        date: 'December 23, 2020',
                        pages: 17,
                        cover: null,
                    },
                    {
                        title: () => 'The Orden Family',
                        date: 'January 6, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Old Man Voll',
                        date: 'January 13, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Statues of Heroes',
                        date: 'January 20, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Reason to Begin the Journey',
                        date: 'January 27, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Emotional Support',
                        date: 'February 3, 2021',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'The First-Class Exam',
                        date: 'February 10, 2021',
                        pages: 21,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Stille—Meteoric Iron Bird',
                        date: 'February 17, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Commence Capture Strategy',
                        date: 'February 24, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Spell to Capture a Bird',
                        date: 'March 3, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Time for Resolve',
                        date: 'March 10, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Reason to Fight',
                        date: 'March 17, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Privilege',
                        date: 'March 24, 2021',
                        pages: 21,
                        cover: null,
                    },
                    {
                        title: () => 'Recapture the Stille',
                        date: 'March 31, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Water-Manipulation Magic',
                        date: 'April 7, 2021',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'An Even-Better Flavor',
                        date: 'April 14, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Fern and Her Baked Sweets',
                        date: 'April 21, 2021',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "The Ruins of the King's Tomb",
                        date: 'April 28, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Dungeons and Magical Items',
                        date: 'May 12, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Spiegel—A Water-Mirror Demon',
                        date: 'May 19, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Dungeon Battle',
                        date: 'May 26, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Strategy Meeting',
                        date: 'June 2, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'An Era of Humans',
                        date: 'June 9, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Spell that Slashes Almost Anything',
                        date: 'June 16, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Second Exam Ends',
                        date: 'June 23, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => "Fern's Staff",
                        date: 'June 30, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Third Exam',
                        date: 'July 7, 2021',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => "Serie's Intuition",
                        date: 'July 14, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'With a Little Help',
                        date: 'July 21, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Departure and Farewell',
                        date: 'July 28, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Magic-Nullifying Crystal',
                        date: 'August 4, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Why I Set Out on This Journey',
                        date: 'August 18, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Hero of the South',
                        date: 'August 25, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Demon with a Sword',
                        date: 'September 1, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () =>
                            'The Secret Hot Spring of the Etwas Mountains',
                        date: 'September 15, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Places She Would Like',
                        date: 'September 22, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Peaceful Time',
                        date: 'September 29, 2021',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Northern Plateau',
                        date: 'October 6, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => "Boshaft—The Emperor's Spirit",
                        date: 'October 13, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Norm Company',
                        date: 'October 20, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Subjugation Request',
                        date: 'November 2, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The General',
                        date: 'November 10, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Encounter Battle',
                        date: 'November 17, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Divine Revolte',
                        date: 'November 24, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Erilfrachte-The Spell to Dispel Fog',
                        date: 'December 1, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Settling',
                        date: 'December 8, 2021',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Thunder of Dragons',
                        date: 'December 22, 2021',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Lake Korridor',
                        date: 'January 5, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Great Tor Canyon',
                        date: 'January 12, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Holy Snow Crystals',
                        date: 'January 19, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Golden Land',
                        date: 'January 26, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () =>
                            'Diagoldze—The Spell to Transmute All Creation into Gold',
                        date: 'February 9, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Stone Bracelet of Servitude',
                        date: 'February 16, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Daredevil',
                        date: 'February 23, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Malice',
                        date: 'March 9, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Discussions',
                        date: 'March 16, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Affection',
                        date: 'March 23, 2022',
                        pages: 17,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Solitär',
                        date: 'March 30, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Guilt',
                        date: 'April 6, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Glück',
                        date: 'April 20, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Onstage',
                        date: 'April 27, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The End of Weise',
                        date: 'May 11, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Great Barrier',
                        date: 'May 18, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Analysis',
                        date: 'June 15, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Nameless Greater Demon',
                        date: 'June 22, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Master and Apprentice',
                        date: 'July 6, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Observation',
                        date: 'July 27, 2022',
                        pages: 24,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Retribution',
                        date: 'August 3, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Offense and Defense',
                        date: 'August 31, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Fundamentals of Mages',
                        date: 'September 21, 2022',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Breakthrough',
                        date: 'October 4, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Draw',
                        date: 'October 12, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Time for Retribution',
                        date: 'October 26, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A Visit to Her Grave',
                        date: 'November 16, 2022',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Golem',
                        date: 'December 7, 2022',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Sky-Mountain Dragon',
                        date: 'December 20, 2022',
                        pages: 28,
                        cover: null,
                    },
                    {
                        title: () => 'The Monument of the Goddess',
                        date: 'January 17, 2023',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Reunion',
                        date: 'March 21, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Zart the Remnant',
                        date: 'March 28, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Party of Heroes',
                        date: 'April 4, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Escort Mission',
                        date: 'September 6, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Faith',
                        date: 'September 13, 2023',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'Abyssal Dragon',
                        date: 'September 27, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'The Sword of the Hero',
                        date: 'October 4, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Best Friend',
                        date: 'October 18, 2023',
                        pages: 19,
                        cover: null,
                    },
                    {
                        title: () => 'Spell to Return',
                        date: 'November 1, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Miraculous Illusion',
                        date: 'November 15, 2023',
                        pages: 20,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Vialathor',
                        date: 'December 6, 2023',
                        pages: 22,
                        cover: null,
                    },
                    {
                        title: () => 'Memories',
                        date: 'December 13, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'False Image of a Hero',
                        date: 'December 27, 2023',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Monsters on the Road',
                        date: 'January 10, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Titan Fortress Ruins',
                        date: 'January 17, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Proof of Perseverance',
                        date: 'January 31, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Shadow Warrior',
                        date: 'February 7, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Family',
                        date: 'February 21, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'A New Mission',
                        date: 'February 28, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Retrieval Mission',
                        date: 'March 13, 2024',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Magic Special Forces',
                        date: 'April 17, 2024',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Shadow of the Empire',
                        date: 'April 24, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => "Beneath the Water's Surface",
                        date: 'May 8, 2024',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Escape',
                        date: 'August 7, 2024',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Chase',
                        date: 'August 28, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Silver Coins',
                        date: 'September 11, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Trace Back',
                        date: 'September 25, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Prelude',
                        date: 'October 9, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Reunion',
                        date: 'October 23, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Repel',
                        date: 'November 6, 2024',
                        pages: 18,
                        cover: null,
                    },
                ],
            },
            {
                title: volumeTitle,
                cover: volumeCover,
                chapters: [
                    {
                        title: () => 'Traitor',
                        date: 'November 20, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Kreis the Blacksmith',
                        date: 'December 11, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Ballroom',
                        date: 'December 25, 2024',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Symbol of Peace',
                        date: 'July 23, 2025',
                        pages: 20,
                        cover: null,
                    },
                    {
                        title: () => 'Enemy Encounter',
                        date: 'August 6, 2025',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Mind Games',
                        date: 'August 20, 2025',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Prophetic Dream',
                        date: 'September 3, 2025',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'Clairvoyance',
                        date: 'September 17, 2025',
                        pages: 16,
                        cover: null,
                    },
                    {
                        title: () => 'The Strongest Warrior',
                        date: 'October 1, 2025',
                        pages: 18,
                        cover: null,
                    },
                    {
                        title: () => 'The Land with No Hero',
                        date: 'October 15, 2025',
                        pages: 16,
                        cover: null,
                    },
                ],
            },
        ] as const satisfies Tuple<Volume, typeof VOLUMES_TOTAL>,
        arcs: [
            {
                title: "Beyond Journey's End",
                cover: 'Chapter_1_(clean)',
                offset: { x: 0, y: 170 },
                chapters: { from: 1, to: 13 },
            },
            {
                title: 'Aura the Guillotine',
                cover: 'Volume_3_(clean)',
                offset: { x: 0, y: 380 },
                chapters: { from: 14, to: 23 },
            },
            {
                title: 'Travels to Äußerst',
                cover: 'Volume_4_(clean)',
                offset: { x: 0, y: 200 },
                chapters: { from: 24, to: 36 },
            },
            {
                title: 'First-Class Mage Exam', // divide stages?
                cover: 'Volume_5_(clean)',
                offset: { x: 0, y: 760 },
                chapters: { from: 37, to: 60 },
            },
            {
                title: 'Continued Northern Travels',
                cover: 'Volume_7_(clean)',
                offset: { x: 0, y: 440 },
                chapters: { from: 61, to: 70 },
            },
            {
                title: 'Divine Revolte',
                cover: 'Chapter_74',
                offset: { x: 50, y: 0 },
                chapters: { from: 71, to: 76 },
            },
            {
                title: 'The Golden Land',
                cover: 'Chapter_87',
                offset: { x: 0, y: 350 },
                chapters: { from: 77, to: 104 },
            },
            {
                title: "Goddess's Monument",
                cover: 'Chapter_107_color_page_2',
                offset: { x: 0, y: 0 },
                chapters: { from: 105, to: 119 },
            },
            {
                title: 'Imperial Territory Travels',
                cover: 'Chapter_124',
                offset: { x: 0, y: 0 },
                chapters: { from: 120, to: 125 },
            },
            {
                title: 'Foundation Festival',
                cover: 'Chapter_143',
                offset: { x: 0, y: 1040 },
                chapters: { from: 126 },
            },
        ] as const satisfies Tuple<Arc, typeof ARCS_TOTAL>,
        seasons: [
            {
                title: "Frieren: Beyond Journey's End Season 1",
                cover: (_, idx) => `Season_${idx + 1}_key_visual_3`,
                offset: { x: 0, y: 4650 },
                chapters: { from: 1, to: 60 },
                episodes: [
                    {
                        title: () => "The Journey's End",
                        cover: episodeCover,
                        offset: { x: 120, y: 0 },
                        chapters: { from: 1, to: 2 },
                    },
                    {
                        title: () => "It Didn't Have to Be Magic...",
                        cover: episodeCover,
                        offset: { x: 150, y: 0 },
                        chapters: { from: 2, to: 3 },
                    },
                    {
                        title: () => 'Killing Magic',
                        cover: episodeCover,
                        offset: { x: 250, y: 0 },
                        chapters: { from: 4, to: 5 },
                    },
                    {
                        title: () => 'The Land Where Souls Rest',
                        cover: episodeCover,
                        offset: { x: 170, y: 0 },
                        chapters: { from: 6, to: 8 },
                    },
                    {
                        title: () => 'Phantoms of the Dead',
                        cover: episodeCover,
                        offset: { x: 70, y: 0 },
                        chapters: { from: 8, to: 10 },
                    },
                    {
                        title: () => 'The Hero of the Village',
                        cover: episodeCover,
                        offset: { x: 180, y: 0 },
                        chapters: { from: 11, to: 12 },
                    },
                    {
                        title: () => 'Like a Fairy Tale',
                        cover: episodeCover,
                        offset: { x: 200, y: 0 },
                        chapters: { from: 13, to: 15 },
                    },
                    {
                        title: () => 'Frieren the Slayer',
                        cover: episodeCover,
                        offset: { x: 180, y: 0 },
                        chapters: { from: 15, to: 17 },
                    },
                    {
                        title: () => 'Aura the Guillotine',
                        cover: episodeCover,
                        offset: { x: 240, y: 0 },
                        chapters: { from: 18, to: 20 },
                    },
                    {
                        title: () => 'A Powerful Mage',
                        cover: episodeCover,
                        offset: { x: 200, y: 0 },
                        chapters: { from: 21, to: 22 },
                    },
                    {
                        title: () => 'Winter in the Northern Lands',
                        cover: episodeCover,
                        offset: { x: 30, y: 0 },
                        chapters: { from: 23, to: 24 },
                    },
                    {
                        title: () => 'A Real Hero',
                        cover: episodeCover,
                        offset: { x: 140, y: 0 },
                        chapters: { from: 25, to: 26 },
                    },
                    {
                        title: () => "Aversion to One's Own Kind",
                        cover: episodeCover,
                        offset: { x: 190, y: 0 },
                        chapters: { from: 27, to: 28 },
                    },
                    {
                        title: () => 'Privilege of the Young',
                        cover: episodeCover,
                        offset: { x: 260, y: 0 },
                        chapters: { from: 29, to: 30 },
                    },
                    {
                        title: () => 'Smells like Trouble',
                        cover: episodeCover,
                        offset: { x: 200, y: 0 },
                        chapters: { from: 31, to: 32 },
                    },
                    {
                        title: () => 'Long-Lived Friends',
                        cover: episodeCover,
                        offset: { x: 80, y: 0 },
                        chapters: { from: 33, to: 34 },
                    },
                    {
                        title: () => 'Take Care',
                        cover: episodeCover,
                        offset: { x: 190, y: 0 },
                        chapters: { from: 35, to: 36 },
                    },
                    {
                        title: () => 'First-Class Mage Exam',
                        cover: episodeCover,
                        offset: { x: 250, y: 0 },
                        chapters: { from: 37, to: 38 },
                    },
                    {
                        title: () => 'Well-Laid Plans',
                        cover: episodeCover,
                        offset: { x: 290, y: 0 },
                        chapters: { from: 38, to: 41 },
                    },
                    {
                        title: () => 'Necessary Killing',
                        cover: episodeCover,
                        offset: { x: 270, y: 0 },
                        chapters: { from: 41, to: 43 },
                    },
                    {
                        title: () => 'The World of Magic',
                        cover: episodeCover,
                        offset: { x: 130, y: 0 },
                        chapters: { from: 43, to: 45 },
                    },
                    {
                        title: () => 'Future Enemies',
                        cover: episodeCover,
                        offset: { x: 170, y: 0 },
                        chapters: { from: 46, to: 47 },
                    },
                    {
                        title: () => 'Conquering the Labyrinth',
                        cover: episodeCover,
                        offset: { x: 170, y: 0 },
                        chapters: { from: 48, to: 49 },
                    },
                    {
                        title: () => 'Perfect Replicas',
                        cover: episodeCover,
                        offset: { x: 130, y: 0 },
                        chapters: { from: 50, to: 51 },
                    },
                    {
                        title: () => 'A Fatal Vulnerability',
                        cover: episodeCover,
                        offset: { x: 310, y: 0 },
                        chapters: { from: 52, to: 53 },
                    },
                    {
                        title: () => 'The Height of Magic',
                        cover: episodeCover,
                        offset: { x: 230, y: 0 },
                        chapters: { from: 54, to: 55 },
                    },
                    {
                        title: () => 'An Era of Humans',
                        cover: episodeCover,
                        offset: { x: 180, y: 0 },
                        chapters: { from: 56, to: 58 },
                    },
                    {
                        title: () =>
                            'It Would Be Embarrassing When We Met Again',
                        cover: episodeCover,
                        offset: { x: 150, y: 0 },
                        chapters: { from: 58, to: 60 },
                    },
                ],
            },
            {
                title: "Frieren: Beyond Journey's End Season 2",
                cover: (_, idx) => `Season_${idx + 1}_key_visual_3`,
                offset: { x: 0, y: 2000 },
                chapters: { from: 61, to: 125 },
                episodes: [],
            },
            {
                chapters: { from: 126 },
            },
        ] as const satisfies Tuple<Season, typeof SEASONS_TOTAL>,
        splitChapters: {
            2: 13,
            8: 13,
            15: 13,
            38: 17,
            41: 7,
            43: 16,
            58: 5,
        } as const,
        wikiBase: 'https://frieren.fandom.com/wiki/',
        smallImages: {
            'scroller-or-favicon': 'circle',
            'read-info': 'circle',
            'toggle-unbounded-chapter-width': 'circle',
            'toggle-cross-lines': 'circle',
            'open-chapter-calendar': 'circle',
            'toggle-always-show-titles': 'circle',
            'capture-timeline': 'circle',
        },
        socialLinks: [
            {
                name: 'Official Frieren Website',
                url: 'http://frieren-anime.jp/',
            },
            {
                name: 'Official Frieren Twitter',
                url: 'https://twitter.com/anime_frieren',
            },
        ],
    },
};
