name: Deploy Static Content to GitHub Pages

on:
    pull_request:
        branches: ['main']
    push:
        branches: ['main']
        paths-ignore:
            - '**.md'
            - '.github/ISSUE_TEMPLATE/**'
            - '.github/PULL_REQUEST_TEMPLATE/**'
    workflow_dispatch:
        inputs:
            preview:
                description: 'Deploy a preview build'
                required: false
                default: false
                type: boolean
            force_optimize:
                description: 'Force image optimization (ignore cache)'
                required: false
                default: false
                type: boolean

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            force_optimize: ${{ github.event.inputs.force_optimize == true || contains(github.event.head_commit.message, '[force-optimize]') }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' && github.event.inputs.preview == true
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
